import test from 'node:test';import assert from 'node:assert/strict';import {evaluateActionEvidence} from './action_evidence_adapter.mjs';
const now=Date.parse('2026-10-05T06:05:00Z'),sha='a'.repeat(64),read={rawSha256:sha,startedAt:'2026-10-05T06:00:00Z',completedAt:'2026-10-05T06:01:00Z',complete:true,identifiersUnique:true};
function fixture(){return{association:{basis:'owner-attested-recurring-v1',status:'active',expiresAt:'2026-10-10T13:30:00Z'},live:{positions:{...read,contract:'all-open-positions'},orders:{...read,contract:'all-live-orders',currencyVerified:true,remainingQtyVerified:true},balances:{...read,contract:'all-currency-balances',cashBasisVerified:true}},trade:{rawSha256:sha,targetDate:'2026-10-02',accountMatched:true,executionIdsUnique:true,conflict:false,savedSharesightMatched:true,coverageBasis:'declared-activity-interval',fromDate:'2026-10-02',toDate:'2026-10-02',correctionsVerified:true},cash:{rawSha256:sha,accountMatched:true,reportedDate:'2026-10-02',basis:'trade-date',perCurrencyMatched:true,fxBasisVerified:true,conflict:false},consistency:{holdingsTradesCash:'consistent',ordersCash:'consistent',sharesightConfiguration:'consistent'}};}
test('independent complete semantic evidence permits private planning without upstream asof/snapshot/finality claims',()=>{const r=evaluateActionEvidence(fixture(),now);assert.equal(r.status,'eligible-for-private-planning');assert.deepEqual(r.reasonCodes,[]);assert.equal(r.atomicSnapshot,false);assert.equal(r.ledgerFinality,'not-certified');assert.equal(r.actionAmountsIncluded,false);});
test('actual limited shape keeps live reads useful while cash and cancellation coverage remain incomplete',()=>{const f=fixture();delete f.live.balances;f.live.orders.currencyVerified=false;f.trade.coverageBasis='verified-known-executions';delete f.cash;const r=evaluateActionEvidence(f,now);assert.equal(r.levels.positions,'current-read-complete');assert.equal(r.levels.orders,'current-read-complete');assert.equal(r.levels.trades,'known-executions-matched');assert.equal(r.status,'partial');for(const code of ['ORDER_RESERVE_UNVERIFIED','TARGET_SESSION_COVERAGE_UNVERIFIED','TARGET_CASH_UNVERIFIED','CURRENT_CASH_BASIS_UNVERIFIED'])assert.ok(r.reasonCodes.includes(code));});
test('fresh request never fixes duplicate executions, uncovered interval, cash conflict or unexplained holdings change',()=>{for(const change of [f=>f.trade.executionIdsUnique=false,f=>f.trade.toDate='2026-10-01',f=>f.cash.conflict=true,f=>f.consistency.holdingsTradesCash='unexplained']){const f=fixture();change(f);assert.equal(evaluateActionEvidence(f,now).status,'partial');}});
test('future or stale live rows and expired owner association cannot authorize action planning',()=>{for(const change of [f=>f.live.orders.completedAt='2026-10-05T06:06:00Z',f=>f.live.positions.startedAt='2026-10-05T05:00:00Z',f=>f.association.expiresAt='2026-10-04T00:00:00Z']){const f=fixture();change(f);assert.equal(evaluateActionEvidence(f,now).status,'partial');}});

test("invalid calendar dates cannot establish target coverage",()=>{const f=fixture();f.trade.targetDate="2026-02-30";f.trade.fromDate=f.trade.toDate=f.cash.reportedDate=f.trade.targetDate;assert.equal(evaluateActionEvidence(f,now).status,"partial");});
