// All rows, accounts, amounts, completion receipts and archives below are
// SYNTHETIC OFFLINE fixtures. They certify no real production sync or source.
import test from 'node:test';
import assert from 'node:assert/strict';
import {adaptFlexArchive,applyFinancialVerification,adaptPrivateNoahUiExport,digest,readVerifiedSnapshot,SNAPSHOT_SCOPES} from './eod_sources.mjs';
import {runPrivateEodReport,validateEodReceipt} from './eod_report.mjs';
import {runDaily} from './daily.mjs';
import {collectDelivery} from './delivery.mjs';
import {publishPrepared} from './publish.mjs';
import {associationPolicyBlob} from '../../scripts/xuan-ib-account-association.mjs';
import {extractNightActionModel,renderNightActionReport} from '../../scripts/xuan-ib-night-action-view.mjs';
import {validateNightActionHtml} from '../../scripts/xuan-ib-night-action-guard.mjs';
const ACCOUNT='SYNTHETIC_ACCOUNT',QUERY='SYNTHETIC_QUERY',DATE='2026-10-08',NOW=()=>Date.parse('2026-10-09T05:00:00Z');
const tags=attrs=>Object.entries(attrs).map(([k,v])=>`${k}="${v}"`).join(' ');
function archive({extra='',cash=true,positions=true,trades='<Trades/>',residual=0}={}){
  const row=tags({accountId:ACCOUNT,reportDate:DATE,levelOfDetail:'BaseCurrency',currency:'BASE_SUMMARY',endingCash:'200',endingSettledCash:'180',commissions:'-2',fxTranslationGainLoss:'1',netTradesPurchases:'-20',netTradesSales:'10'});
  const native=tags({accountId:ACCOUNT,reportDate:DATE,levelOfDetail:'Currency',currency:'USD',endingCash:'100',endingSettledCash:'90'});
  const foreign=tags({accountId:ACCOUNT,reportDate:DATE,levelOfDetail:'Currency',currency:'HKD',endingCash:'780',endingSettledCash:'702'});
  const p=tags({accountId:ACCOUNT,reportDate:DATE,levelOfDetail:'SUMMARY',conid:'SYNTHETIC_CONTRACT',symbol:'EXUS',currency:'USD',position:'10',multiplier:'1',markPrice:'10',positionValue:'100',fxRateToBase:'1'});
  const bytes=`<AF><FlexStatements><FlexStatement ${tags({accountId:ACCOUNT,fromDate:'2026-10-01',toDate:DATE,whenGenerated:'2026-10-09;00:15:30'})}>${cash?`<CashReport><CashReportCurrency ${row}/><CashReportCurrency ${native}/><CashReportCurrency ${foreign}/></CashReport>`:''}${positions?`<OpenPositions><OpenPosition ${p}/></OpenPositions>`:''}${trades}${extra}</FlexStatement></FlexStatements></AF>`;
  return {bytes,metadata:{privateObject:'synthetic/offline/archive.xml',generation:'1',rawSha256:digest(bytes),configuredQueryId:QUERY,baseCurrency:'USD',providerTimezone:null,cashReconciliationResidual:residual,executionsCoveredThrough:DATE,cancellationsVerified:true}};
}
// Fixed independent synthetic oracle. It certifies ONLY one predeclared XML
// hash/generation/account/cutoff and its separate synthetic receipt/snapshot.
// Financial facts are never copied or echoed from readArchive metadata.
const ORACLE_RAW=digest(archive().bytes);
function financialOracle(facts={cashResidual:0,cashCoveredThrough:DATE,executionsCoveredThrough:DATE,cancellationsComplete:true,cashMovementsComplete:true}){
  const proof={status:'independently-checked',scope:'eod-cash-and-executions',account:ACCOUNT,configuredQueryId:QUERY,sourceDate:DATE,generation:'1',rawSha256:ORACLE_RAW,
    evidence:{receiptSha256:digest('SYNTHETIC INDEPENDENT FINANCIAL RECEIPT'),receiptGeneration:'1',snapshotSha256:digest('SYNTHETIC INDEPENDENT FINANCIAL SNAPSHOT'),snapshotGeneration:'1'},facts:structuredClone(facts)};
  return async({archive:a})=>digest(a.bytes)===ORACLE_RAW?structuredClone(proof):null;
}
const adapt=a=>adaptFlexArchive(a,{expectedAccount:ACCOUNT,expectedQueryId:QUERY,sourceDate:DATE,readAt:new Date(NOW()).toISOString()});
const h=(id,group_name,value,code)=>({id,group_name,value,instrument:{code},quantity:10,instrument_price:10});
function snapshot(key){return {raw:{mode:'read_only',source:'Sharesight User API',data:{report:key==='sharesight.ibGroupedPerformance'?{portfolio_id:936247,currency:{code:'USD'},grouping:'custom_group_category',custom_group:{id:83569,name:'资产类别'},end_date:DATE,holdings:[h(1,'美国底仓',450,'CSPX'),h(2,'美国底仓',50,'USSC'),h(3,'美国科技',250,'GOOG'),h(4,'非美发达',180,'EXUS'),h(5,'新兴市场',70,'EIMI'),h(6,'防御资产',90,'TLT')],cash_accounts:[]}:{portfolio_id:936238,currency:{code:'USD'},end_date:DATE,cash_accounts:[{value:50}]}}},synthetic:true};}
// A normalized proof emitted ONLY by this synthetic test verifier. No assumed
// real producer schema, storage address or receipt is asserted by this fixture.
const verifySnapshot=async({envelope,sourceKey,sourceDate,rawFingerprint})=>{assert.equal(envelope.synthetic,true);return {status:'sync-completed',sourceKey,sourceDate,rawSha256:rawFingerprint,receiptSha256:digest('SYNTHETIC RECEIPT '+sourceKey),snapshotGeneration:'1',completedAt:'2026-10-09T04:30:00Z'};};
function context(){const policy={schemaVersion:1,policyId:'ib-primary-7day-pilot-v1',accountAlias:'IB-HK',basis:'owner-attested-recurring-v1',status:'active',purpose:'xuan-ib-read-only-report',editions:['adhoc','am','pm'],publisher:'codex-verified-candidate-v1',validFrom:'2026-09-11T13:30:00.000Z',expiresAt:'2026-10-10T13:30:00.000Z'};return {association:{policy,policyCommit:'a'.repeat(40),policyBlob:associationPolicyBlob(policy),checkedAt:new Date(NOW()).toISOString()},previousSourceSha:'c'.repeat(40),reserveHash:'b'.repeat(64),reserveLedger:{schemaVersion:1,purpose:'xuan-etf-owner-declared-pending-calls',entries:[{date:'2026-10-01',usd:50}]},previousHtml:''};}
function live(orders=[]){const source=(sourceKey,raw)=>({sourceKey,raw,startedAt:new Date(NOW()).toISOString(),completedAt:new Date(NOW()).toISOString()});return {status:'captured',asOfHkt:'2026-10-09 13:00 HKT',sources:[source('ib.accountSummary',{currency:'USD',total_cash_value:999}),source('ib.positions',{positions:[{contract_description:'EXUS',position:10,market_price:10,market_value:100,currency:'USD'}]}),source('ib.orders',{orders})]};}
const order=(side,quantity='2')=>({order_id:side==='BUY'?1:2,order_status:'NEW',order_type:'LIMIT',side,limit_price:'10',total_shares_qty:quantity,cum_shares_qty:'0',remaining_shares_qty:quantity,primary_description:`${side==='BUY'?'Buy':'Sell'} ${quantity} EXUS`,secondary_description:'Synthetic description',order_time:'2026-10-08T14:00:00Z'});
function harness(overrides={}){const objects=new Map(),c=context(),calls=[];const io={savePrivate:async(name,value)=>{if(objects.has(name))throw new Error('IMMUTABLE_OBJECT_EXISTS');objects.set(name,value);return {sha256:digest(value),generation:'1'};},loadGatewayToken:()=>{throw new Error('FORBIDDEN_CREDENTIAL');},ibStore:new Proxy({}, {get(){throw new Error('FORBIDDEN_CREDENTIAL');}})};return {objects,c,calls,io,options:{sourceDate:DATE,io,now:NOW,loadContext:async()=>c,readArchive:async()=>archive(),verifyArchive:async({archive:a,expectedAccount,expectedQueryId,sourceDate})=>({status:'archive-verified',rawSha256:digest(a.bytes),account:expectedAccount,configuredQueryId:expectedQueryId,sourceDate,generation:a.metadata.generation}),verifyArchiveFinancial:financialOracle(),expectedAccount:ACCOUNT,expectedQueryId:QUERY,snapshotReader:async({sourceKey})=>{calls.push(sourceKey);return snapshot(sourceKey);},verifySnapshotCompletion:verifySnapshot,...overrides}};}
async function result(overrides={}){const h=harness(overrides),receipt=await runPrivateEodReport(h.options),html=h.objects.get(receipt.artifact.privateObject);return {...h,receipt,html,model:extractNightActionModel(html)};}
// Entire UI fixture is synthetic. Scope comes from the pre-existing registry;
// no real holding names, report identity, source hashes or amounts are copied.
function uiFixture(){
  const scope=SNAPSHOT_SCOPES['sharesight.noahPerformance'];
  const row=(n,cells)=>({row:String(n),cells:Object.fromEntries(Object.entries(cells).map(([k,v])=>[k+n,v]))});
  const header=['Market','Code','Name','Price','Quantity','Value (us$)','Capital Gains','Capital Gains Percentage','Dividends','Dividends Percentage','Currency','Currency Percentage','Return','Return Percentage','Investment Type','Labels'];
  const head=n=>row(n,Object.fromEntries(header.map((v,i)=>[String.fromCharCode(65+i),v])));
  const top=()=>[row(1,{A:`Performance Report for ${scope.portfolio}`}),row(2,{A:'Showing performance by Investment type between dates 1 Jan 2025 to 8 Oct 2026'}),row(3,{A:'Excluding sold shares'})];
  return {provenance:{portfolio_id:scope.portfolioId,portfolio:scope.portfolio,report_id:123,source_url:`https://portfolio.sharesight.com/portfolios/${scope.portfolioId}/tools/performance/123?consolidated=false`,report_start:'2025-01-01',report_end:DATE,report_timezone:'America/New_York',grouping:'Investment type',include_closed_positions:false,original_start_date_preserved:true,captured_utc:'2026-10-09T04:40:00Z',export_xlsx_utc:'2026-10-09T04:41:00Z'},file_hashes:{'synthetic.xlsx':digest('SYNTHETIC XLSX'),'synthetic.pdf':digest('SYNTHETIC PDF')},original_export_cells:[...top(),head(5),row(6,{C:scope.portfolio,F:'42.35',O:'Cash Accounts'}),row(7,{A:'Total'}),...top(),row(4,{A:'Grouping 1 Cash Accounts'}),head(6),row(7,{C:scope.portfolio,F:'42.35',O:'Cash Accounts'}),row(8,{A:'Total'})]};
}
const uiAdapt=input=>{const bytes=JSON.stringify(input);return adaptPrivateNoahUiExport({bytes,expectedTransferSha256:digest(bytes)},{sourceDate:DATE,reportStart:'2025-01-01',now:NOW});};
test('official UI cash extract stays private and preserves original range without API/sync/annualised-daily claims',async()=>{
  const ui=uiAdapt(uiFixture());assert.equal(ui.status,'ui-export-observed');assert.equal(ui.uiCash.total,42.35);assert.equal(ui.completion,null);assert.equal(Object.hasOwn(ui,'raw'),false);
  assert.equal(ui.provenance.uiReportStart,'2025-01-01');assert.equal(ui.privateSource.periodReturnsNotDaily,true);assert.equal(ui.privateSource.originalBinaryHashesLocallyVerified,false);assert.equal(ui.privateSource.automaticApiReaderTested,false);
  const {buildEodActionModel}=await import('../../scripts/xuan-ib-eod-action-model.mjs');
  const {classifySleepPublication}=await import('../../scripts/xuan-ib-sleep-priority.mjs');
  const ib=await readVerifiedSnapshot('sharesight.ibGroupedPerformance',{sourceDate:DATE,now:NOW,reader:async()=>snapshot('sharesight.ibGroupedPerformance')});
  for(const capture of [null,live()]){
    const flex=applyFinancialVerification(adapt(archive()),await financialOracle()({archive:archive()}),{expectedAccount:ACCOUNT,expectedQueryId:QUERY,sourceDate:DATE,generation:'1'});
    const sourceOutcomes=[{sourceKey:'ib.flexEod',status:'verified',rawFingerprint:flex.rawFingerprint},...([ib,ui].map(s=>({sourceKey:s.sourceKey,status:s.status,rawFingerprint:s.rawFingerprint}))),{sourceKey:'ib.optionalLive',status:capture?'captured':'not-called',rawFingerprint:capture?digest(capture):null}];
    const model=buildEodActionModel({dataDate:'2026-10-09',sourceDate:DATE,asOfHkt:'2026-10-09 13:00 HKT · 数据至 '+DATE,flex,snapshots:[ib,ui],live:capture,reserve:50,sourceOutcomes});
    assert.equal(model.cash.noah,42.35);assert.equal(model.cash.pool,242.35);assert.equal(model.allocation.status,'ready');assert.equal(model.cash.planning,null);assert.equal(model.cash.executableBudget,null);
    const html=renderNightActionReport(model);assert.ok(html.includes('官方 UI 导出'));assert.ok(html.includes('2025-01-01 至 '+DATE));assert.ok(html.includes('区间收益非单日；仅私有验收'));assert.ok(!html.includes('synthetic.xlsx'));
    assert.throws(()=>classifySleepPublication(html),/private acceptance only/);
    // A fully bound synthetic receipt must still hit the explicit private-only
    // boundary before any publisher request, not fail an earlier hash check.
    const r=await result();const receipt=structuredClone(r.receipt);for(const s of receipt.sources)s.rawFingerprint=model.sourceOutcomes.find(o=>o.sourceKey===s.sourceKey).rawFingerprint;
    model.sourceManifestSha256=digest(receipt.sources.map(s=>({sourceKey:s.sourceKey,privateObject:s.privateObject,generation:s.generation,sha256:s.sha256,rawFingerprint:s.rawFingerprint})).sort((a,b)=>a.sourceKey.localeCompare(b.sourceKey)));
    model.evidenceSha256=digest({sourceOutcomes:model.sourceOutcomes,sourceManifestSha256:model.sourceManifestSha256});
    const bound=renderNightActionReport(model);receipt.sourceOutcomes=model.sourceOutcomes;receipt.sourceManifestSha256=model.sourceManifestSha256;receipt.evidenceSha256=model.evidenceSha256;receipt.artifact.sha256=digest(bound);
    assert.throws(()=>validateEodReceipt(receipt,bound,'2026-10-09',DATE),/UI_EXPORT_PRIVATE_ONLY/);
    let calls=0;await assert.rejects(publishPrepared({html:bound,receipt,now:NOW,loadContext:async()=>r.c,request:async()=>{calls++;}}),/UI_EXPORT_PRIVATE_ONLY/);assert.equal(calls,0);
  }
  const automatic=await result({snapshotReader:async({sourceKey})=>sourceKey==='sharesight.noahPerformance'?ui:snapshot(sourceKey)});
  assert.equal(automatic.model.cash.noah,null);assert.equal(automatic.model.sourceOutcomes[2].status,'missing-fields');
});
test('UI cash adapter rejects cutoff/group/currency/cash conflict, malformed rows, source identity and transfer tampering',()=>{
  const mutations=[x=>x.provenance.report_end='2026-10-07',x=>x.provenance.report_start='2025-01-02',x=>x.provenance.include_closed_positions=true,x=>x.provenance.grouping='Other',x=>x.provenance.source_url='https://example.invalid/',x=>x.provenance.portfolio_id=-1,x=>x.provenance.export_xlsx_utc='2026-10-10T05:00:00Z',x=>x.original_export_cells[1].cells.A2='Showing current performance',x=>x.original_export_cells[3].cells.F5='Value (eur)',x=>x.original_export_cells[12].cells.F7='43.35',x=>x.original_export_cells[4].cells.F6='-1',x=>x.original_export_cells[4].cells.F6='NaN',x=>x.original_export_cells[4].cells.D6='42',x=>x.original_export_cells.splice(4,0,structuredClone(x.original_export_cells[4]))];
  for(const mutate of mutations){const input=uiFixture();mutate(input);assert.throws(()=>uiAdapt(input),/EOD_UI_EXPORT_/);}
  assert.throws(()=>adaptPrivateNoahUiExport({bytes:JSON.stringify(uiFixture()),expectedTransferSha256:'f'.repeat(64)},{sourceDate:DATE,reportStart:'2025-01-01',now:NOW}),/UI_EXPORT_BYTES/);
});
test('valid EOD + optional MCP OAuth failure preserves original four cards, unknown orders and safe provenance',async()=>{const r=await result({captureOptionalLive:async()=>{throw new Error('Synthetic OAuth failure');}});assert.deepEqual(r.calls,['sharesight.ibGroupedPerformance','sharesight.noahPerformance']);assert.equal(r.model.schemaVersion,9);assert.equal(r.model.orders.buys,null);assert.equal(r.model.orders.sells,null);assert.equal(r.model.cash.orderReserve,null);assert.equal(r.model.cash.planning,null);assert.equal(r.model.allocation.projectedTotal,null);assert.equal(r.model.cash.pool,250);assert.equal(r.model.cash.ib,200);assert.equal(r.model.cash.eod.settled,180);assert.equal(r.model.cash.cashLike.total,90);assert.equal(r.model.replenishment.status,'unavailable');assert.ok(r.model.allocation.fundingNeed.fullNeed>0);for(const title of ['本轮补仓','挂单提醒','现金优先补仓参考','股票四类配置'])assert.ok(r.html.includes(title));assert.ok(r.html.includes('时区未声明'));assert.equal(validateNightActionHtml(r.html,'2026-10-09').orderCount,null);assert.equal(renderNightActionReport(r.model),r.html);const marker=JSON.stringify(r.model);assert.ok(!marker.includes(ACCOUNT)&&!marker.includes('synthetic/offline')&&!marker.includes('accountId'));assert.ok(r.html.includes("show(\"部分更新\""));assert.equal(r.model.cash.executableBudget,null);});
test('genuine empty orders remain verified empty; BUY reserves remaining limit, SELL never proceeds; EOD wins over live cash',async()=>{const empty=await result({captureOptionalLive:async()=>live()});assert.deepEqual(empty.model.orders.buys,[]);assert.equal(empty.model.cash.orderReserve,0);assert.equal(empty.model.cash.planning,225);assert.equal(empty.model.allocation.projectedTotal,1000);assert.equal(empty.model.replenishment.items[2].amount,22.5);const r=await result({captureOptionalLive:async()=>live([order('BUY'),order('SELL','5')])});assert.equal(r.model.cash.orderReserve,20);assert.equal(r.model.cash.callApplied,25);assert.equal(r.model.cash.planning,205);assert.equal(r.model.allocation.projectedTotal,1020);assert.equal(r.model.orders.sells.length,1);assert.equal(r.model.replenishment.items[2].amount,20.5);assert.equal(r.model.replenishment.executableBudget,null);assert.equal(validateNightActionHtml(r.html,'2026-10-09').orderCount,2);});
test('raw archive binding, configured query, account and cutoff fail closed',()=>{for(const edit of [a=>a.metadata.rawSha256='f'.repeat(64),a=>a.metadata.configuredQueryId='OTHER',a=>{a.bytes=a.bytes.replaceAll(ACCOUNT,'OTHER');a.metadata.rawSha256=digest(a.bytes);},a=>{a.bytes=a.bytes.replaceAll(DATE,'2026-10-07');a.metadata.rawSha256=digest(a.bytes);},a=>{a.bytes=a.bytes.replace('reportDate="2026-10-08"','reportDate="2026-10-07"');a.metadata.rawSha256=digest(a.bytes);},a=>{a.bytes='<!DOCTYPE x>'+a.bytes;a.metadata.rawSha256=digest(a.bytes);}]){const a=archive();edit(a);assert.throws(()=>adapt(a));}});
test('native/base cash do not double count; duplicate base/currency and missing cash remain explicit',()=>{const f=adapt(archive());assert.equal(f.cash.tradeDate,200);assert.equal(f.cash.native.length,2);assert.equal(f.provenance.providerTimezone,null);assert.equal(f.provenance.providerGeneratedText,'2026-10-09;00:15:30');assert.equal(adapt(archive({cash:false})).cash,null);const a=archive();a.bytes=a.bytes.replace('levelOfDetail="Currency"','levelOfDetail="BaseCurrency"');a.metadata.rawSha256=digest(a.bytes);assert.throws(()=>adapt(a),/CURRENCY_SCOPE/);});
test('cash-only source and corrected duplicates retain unknown financial finality without independent proof',()=>{const cash=adapt(archive({positions:false,trades:''}));assert.equal(cash.positions,null);assert.equal(cash.trades,null);assert.equal(cash.tradeCoverageProven,false);const t=`<Trade ${tags({accountId:ACCOUNT,reportDate:DATE,levelOfDetail:'EXECUTION',tradeID:'SYNTHETIC_TRADE',ibExecID:'SYNTHETIC_EXEC',conid:'SYNTHETIC_CONTRACT',buySell:'BUY',currency:'USD',tradeDate:DATE,quantity:'2',tradePrice:'10',netCash:'-22',ibCommission:'-2',origTradeID:'SYNTHETIC_ORIGINAL',transactionType:'CANCEL'})}/>`;const f=adapt(archive({trades:`<Trades>${t}${t}</Trades>`}));assert.equal(f.trades.length,1);assert.equal(f.duplicateRows,1);assert.equal(f.tradeCoverageProven,false);assert.equal(f.reconciliation.cancellationPending,true);assert.equal(adapt(archive({residual:1})).tradeCoverageProven,false);});
test('snapshot scope failures are distinct; invalid completion claims retain only dated API facts',async()=>{const key='sharesight.ibGroupedPerformance',base={sourceDate:DATE,now:NOW,verifyCompletion:verifySnapshot};for(const [status,reader,verifier] of [['request-failure',async()=>{throw Error('fail');}],['missing-fields',async()=>({})],['date-mismatch',async()=>{const s=snapshot(key);s.raw.data.report.end_date='2026-10-07';return s;}],['malformed',async()=>{const s=snapshot(key);s.raw.data.report.portfolio_id=1;return s;}],['date-verified',async()=>snapshot(key),async()=>({status:200})],['date-verified',async()=>snapshot(key),async()=>({owner:'synthetic',lease_until:'2099-01-01'})]])assert.equal((await readVerifiedSnapshot(key,{...base,reader,verifyCompletion:verifier??verifySnapshot})).status,status);assert.equal((await readVerifiedSnapshot(key,{sourceDate:DATE})).status,'not-called');});
test('dated Sharesight facts do not require a new sync receipt or broker positions/executions archive',async()=>{
  for(const verifySnapshotCompletion of [undefined,async()=>null,async()=>{throw Error('SYNTHETIC_COMPLETION_UNAVAILABLE');}]){
    const r=await result({verifySnapshotCompletion,verifyArchiveFinancial:null,readArchive:async()=>archive({positions:false,trades:''})});
    assert.equal(r.model.allocation.status,'ready');assert.equal(r.model.cash.noah,50);assert.equal(r.model.cash.cashLike.total,90);
    assert.ok(r.model.allocation.fundingNeed.fullNeed>0);
    assert.deepEqual(r.model.sourceOutcomes.slice(1,3).map(s=>s.status),['date-verified','date-verified']);
    for(const s of r.model.provenance.sharesight){assert.equal(s.syncCompletedAt,null);assert.equal(s.receiptSha256,null);assert.equal(s.snapshotGeneration,null);}
    assert.ok(r.html.includes('按 API 日期读取；同步完成未核实'));assert.ok(!r.html.includes('同步完成 null'));
    assert.equal(r.model.orders.buys,null);assert.equal(r.model.cash.orderReserve,null);assert.equal(r.model.cash.planning,null);
    assert.equal(r.model.reconciliation.status,'unknown');assert.equal(r.model.cash.executableBudget,null);
    for(const edit of [m=>m.provenance.sharesight[0].syncCompletedAt='2026-10-09T04:30:00.000Z',m=>m.provenance.sharesight[0].receiptSha256='f'.repeat(64),m=>m.provenance.sharesight[0].snapshotGeneration='1']){
      const m=structuredClone(r.model);edit(m);assert.throws(()=>renderNightActionReport(m),/SYNC_COMPLETION_CLAIM/);
    }
  }
});
test('one malformed Sharesight component preserves other valid source outcomes and cash; source date cannot be stale/mixed',async()=>{const r=await result({snapshotReader:async({sourceKey})=>{const s=snapshot(sourceKey);if(sourceKey==='sharesight.ibGroupedPerformance')s.raw.data.report.holdings[0].group_name='Unknown';return s;}});assert.equal(r.model.allocation.status,'unavailable');assert.equal(r.model.cash.noah,50);assert.equal(r.model.cash.ib,200);assert.equal(r.model.cash.cashLike,null);assert.equal(r.model.sourceOutcomes[1].status,'malformed');const r2=await result({snapshotReader:async({sourceKey})=>{const s=snapshot(sourceKey);if(sourceKey==='sharesight.noahPerformance')s.raw.data.report.end_date='2026-10-07';return s;}});assert.equal(r2.model.allocation.status,'ready');assert.equal(r2.model.cash.noah,null);assert.equal(r2.model.cash.pool,null);for(const sourceDate of ['2026-10-07','2026-10-09','2026-02-30']){const h=harness({sourceDate});await assert.rejects(runPrivateEodReport(h.options),/COMPLETED_SESSION/);assert.equal(h.calls.length,0);}});
test('bounded optional failure and malformed orders cannot discard EOD or masquerade as empty',async()=>{const timeout=await result({captureOptionalLive:async({signal})=>new Promise(resolve=>signal.addEventListener('abort',()=>resolve({status:'failed'}))),optionalTimeoutMs:2});assert.equal(timeout.model.sourceOutcomes[3].status,'timeout');const malformed=await result({captureOptionalLive:async()=>live([{}])});assert.equal(malformed.model.orders.status,'unknown');assert.equal(malformed.model.cash.orderReserve,null);});
test('daily/delivery/publisher roundtrip keeps partial capabilities, evidence, calendar and immutable markers',async()=>{const h=harness();await runDaily({io:h.io,now:NOW,execution:'xuan-preopen-report-synthetic',generate:o=>runPrivateEodReport({...h.options,...o})});const receipt=h.objects.get('delivery/2026-10-09/receipt.json'),html=h.objects.get('delivery/2026-10-09/report.html');validateEodReceipt(receipt,html,'2026-10-09',DATE);await assert.rejects(runDaily({io:h.io,now:NOW,execution:'xuan-preopen-report-synthetic',generate:()=>{throw Error('must not run twice');}}),/IMMUTABLE/);const delivered=await collectDelivery({now:NOW,loadContext:async()=>h.c,request:async url=>{const object=decodeURIComponent(new URL(url).pathname.split('/o/')[1]);return object.endsWith('receipt.json')?JSON.stringify(receipt):html;}});assert.equal(delivered.outcome,'reused');let calls=0;const request=async p=>{calls++;if(p.query.startsWith('query'))return {data:{viewer:{login:'huanwujoy-crypto'},repository:{id:'synthetic',ref:{target:{oid:'a'.repeat(40)}}}}};if(p.query.includes('CreateRef'))return {data:{createRef:{ref:{name:p.variables.input.name,target:{oid:'a'.repeat(40)}}}}};return {data:{createCommitOnBranch:{commit:{oid:'d'.repeat(40)},ref:{name:p.variables.input.branch.branchName}}}};};const out=await publishPrepared({html,receipt,now:NOW,loadContext:async()=>h.c,request});assert.equal(out.publication,'candidate-only');assert.equal(calls,3);});
test('receipt evidence/model tampering blocks before publisher requests; complete same-date report cannot be overwritten',async()=>{const r=await result();for(const edit of [x=>x.receipt.evidenceSha256='f'.repeat(64),x=>x.receipt.sources[0].generation='',x=>x.receipt.sourceOutcomes[0].rawFingerprint='f'.repeat(64),x=>x.html+='tamper']){const x={html:r.html,receipt:structuredClone(r.receipt)};edit(x);let calls=0;await assert.rejects(publishPrepared({...x,now:NOW,loadContext:async()=>r.c,request:async()=>{calls++;throw Error('must not request');}}));assert.equal(calls,0);}const empty=await result({captureOptionalLive:async()=>live()});const old={...empty.model,schemaVersion:5};delete old.mode;old.status='ready';old.cash.status='ready';old.replenishment.executableBudget=null;old.allocation.projectedTotal=1000;old.notes=[];r.c.previousHtml=renderNightActionReport(old);let calls=0;await assert.rejects(publishPrepared({html:r.html,receipt:r.receipt,now:NOW,loadContext:async()=>r.c,request:async()=>{calls++;}}),/COMPLETE_REPORT_EXISTS/);assert.equal(calls,0);});
test('stale/future optional capture and unknown currency cannot manufacture reserves or projection',async()=>{for(const edit of [l=>l.sources[0].startedAt='2026-10-09T04:00:00Z',l=>l.sources[0].completedAt='2026-10-09T06:00:00Z',l=>l.sources[1].raw.positions[0].currency='EUR']){const r=await result({captureOptionalLive:async()=>{const l=live([order('BUY')]);edit(l);return l;}});assert.equal(r.model.orders.status,'unknown');assert.equal(r.model.cash.planning,null);assert.equal(r.model.allocation.projectedTotal,null);}});
test('model guard rejects unknown-to-zero, source/capability claims, altered formulas and public private-field additions',async()=>{const r=await result(),complete=await result({captureOptionalLive:async()=>live([order('BUY')])});for(const [base,edit] of [[r.model,m=>m.orders.buys=[]],[r.model,m=>m.cash.orderReserve=0],[r.model,m=>m.cash.executableBudget=1],[r.model,m=>m.sourceOutcomes[1].status='failed'],[r.model,m=>m.provenance.flex.archiveSha256='f'.repeat(64)],[r.model,m=>m.provenance.flex.privateObject='SYNTHETIC_PRIVATE_PATH'],[r.model,m=>m.cash.eod.native[0].accountId=ACCOUNT],[r.model,m=>m.allocation.fundingNeed.fullNeed+=100],[complete.model,m=>{m.replenishment.items[0].amount+=1;m.replenishment.items[1].amount-=1;}],[complete.model,m=>m.sourceOutcomes[3].status='not-called']]){const m=structuredClone(base);edit(m);assert.throws(()=>renderNightActionReport(m));}});
test('pre-close NYSE source, unverified archive, base changes and uploads fail before completed receipt',async()=>{const preclose=harness({now:()=>Date.parse('2026-10-08T17:00:00Z')});await assert.rejects(runPrivateEodReport(preclose.options),/COMPLETED_SESSION/);for(const options of [{verifyArchive:async()=>({status:'archive-verified'})},{loadContext:(()=>{let reads=0;return async()=>{const c=context();if(++reads===2)c.previousSourceSha='e'.repeat(40);return c;};})()}]){const h=harness(options);await assert.rejects(runPrivateEodReport(h.options));assert.equal(h.objects.size,0);}const h=harness();h.io.savePrivate=async()=>{throw Error('SYNTHETIC_SAVE_FAILURE');};await assert.rejects(runPrivateEodReport(h.options),/SAVE_FAILURE/);});
// Round-two acceptance regressions for all eight Astra findings. These assert
// rejection or corrected behavior, never the unsafe behavior reproduced in R1.
test('R1 optional raw error details remain private and all public reasons/timezones/notes are constrained',async()=>{
  const secret='SYNTHETIC_ACCOUNT gs://synthetic-private/error Bearer SYNTHETIC_TOKEN';
  const r=await result({captureOptionalLive:async()=>({status:'failed',code:secret})});
  assert.equal(r.model.orders.reason,'OPTIONAL_LIVE_FAILED');assert.ok(!JSON.stringify(r.model).includes(secret));assert.ok(!r.html.includes(secret));
  for(const edit of [m=>m.orders.reason=secret,m=>m.provenance.flex.providerTimezone=secret,m=>m.notes[0]=secret,m=>m.cash.availableFunds.reason=secret]){const m=structuredClone(r.model);edit(m);assert.throws(()=>renderNightActionReport(m));}
});
test('R2 private immutable source descriptors and raw fingerprints bind to the public manifest digest at every boundary',async()=>{
  const r=await result();assert.equal(r.model.sourceManifestSha256,r.receipt.sourceManifestSha256);assert.ok(!JSON.stringify(r.model).includes('report-check/'));
  for(const edit of [x=>x.sources[0].sha256='e'.repeat(64),x=>x.sources[0].generation='22',x=>x.sources[0].privateObject=x.sources[0].privateObject.replace('report-check/','other/'),x=>x.sources[0].rawFingerprint='e'.repeat(64),x=>x.sources[0].extra='SYNTHETIC_PRIVATE']){
    const receipt=structuredClone(r.receipt);edit(receipt);assert.throws(()=>validateEodReceipt(receipt,r.html,'2026-10-09',DATE));let calls=0;
    await assert.rejects(publishPrepared({html:r.html,receipt,now:NOW,loadContext:async()=>r.c,request:async()=>{calls++;}}));assert.equal(calls,0);
    const delivery={...receipt,artifact:{...receipt.artifact,privateObject:'delivery/2026-10-09/report.html'}};
    await assert.rejects(collectDelivery({now:NOW,loadContext:async()=>r.c,request:async url=>decodeURIComponent(new URL(url).pathname).endsWith('receipt.json')?JSON.stringify(delivery):r.html}));
  }
  const h=harness();h.io.savePrivate=async()=>({sha256:'e'.repeat(64),generation:'1'});await assert.rejects(runPrivateEodReport(h.options),/SAVED_SOURCE_BINDING/);
});
test('R3 richer same-date EOD and schema5 partials survive a weaker candidate, including a final context refresh',async()=>{
  const next=await result(),rich=await result({captureOptionalLive:async()=>live([order('BUY')])});
  const schema5=structuredClone(rich.model);schema5.schemaVersion=5;schema5.cash.status='ready';schema5.status='partial';schema5.notes=[];
  for(const oldHtml of [rich.html,renderNightActionReport(schema5)]){next.c.previousHtml=oldHtml;let calls=0;await assert.rejects(publishPrepared({html:next.html,receipt:next.receipt,now:NOW,loadContext:async()=>next.c,request:async()=>{calls++;}}),/COMPLETE_REPORT_EXISTS/);assert.equal(calls,0);}
  next.c.previousHtml='';let reads=0,calls=0;await assert.rejects(publishPrepared({html:next.html,receipt:next.receipt,now:NOW,loadContext:async()=>({...next.c,previousHtml:++reads===1?'':rich.html}),request:async p=>{calls++;if(p.query.startsWith('query'))return {data:{viewer:{login:'huanwujoy-crypto'},repository:{id:'synthetic',ref:{target:{oid:'a'.repeat(40)}}}}};return {data:{createRef:{ref:{name:p.variables.input.name,target:{oid:'a'.repeat(40)}}}}};}}),/COMPLETE_REPORT_EXISTS/);assert.equal(calls,2);
});
test('R5 and R8 pending/nonzero/unknown reconciliation suppresses every budget; valid planning is an explicit EOD assumption',async()=>{
  for(const options of [{positions:false,trades:'',residual:0},{residual:.004},{residual:-.004},{residual:100},{residual:null}]){const r=await result({readArchive:async()=>archive(options),verifyArchiveFinancial:financialOracle({cashResidual:options.residual,cashCoveredThrough:DATE,executionsCoveredThrough:options.trades===''?null:DATE,cancellationsComplete:true,cashMovementsComplete:true}),captureOptionalLive:async()=>live()});assert.equal(r.model.cash.planning,null);assert.equal(r.model.cash.totalCapacity,null);assert.equal(r.model.replenishment.status,'unavailable');assert.equal(r.model.cash.ib,200);assert.equal(r.model.allocation.status,'ready');assert.ok(r.html.includes('EOD 现金对账尚未核实'));assert.equal(r.model.cash.planningBasis.reason,'EOD_RECONCILIATION_UNRESOLVED');assert.equal(r.model.reconciliation.status,options.residual===null||options.trades===''?'unknown':'pending');}
  const r=await result({captureOptionalLive:async()=>live()});assert.equal(r.model.cash.planningBasis.status,'conditional');assert.equal(r.model.cash.planningBasis.assumption,'NO_UNREFLECTED_ACTIVITY_SINCE_EOD');assert.ok(r.html.includes('假设 EOD 后没有未反映的成交、资金或持仓变化'));
  for(const edit of [m=>m.cash.planningBasis.assumption='VERIFIED_CURRENT',m=>m.reconciliation.cashResidual=.004,m=>m.reconciliation.status='pending']){const m=structuredClone(r.model);edit(m);assert.throws(()=>renderNightActionReport(m));}
});
test('R6 complete XML grammar rejects duplicate paired/empty sections, wrong topology, malformed roots and row nesting',()=>{
  for(const edit of [s=>s.replace('<Trades/>','<Trades/><Trades/>'),s=>s.replace('<Trades/>','<Trades/><Trades></Trades>'),s=>s.replace('<Trades/>','<Trades></Trades><Trades/>'),s=>s.replace('</AF>',''),s=>s.replace('<CashReport>','<Wrapper><CashReport>').replace('</CashReport>','</CashReport></Wrapper>'),s=>s.replace('<AF>','<Bogus>'),s=>s.replace('</FlexStatement>','</Unknown>'),s=>s.replace('<Trades/>','<Trades><Wrapper><Trade/></Wrapper></Trades>')]){const a=archive();a.bytes=edit(a.bytes);a.metadata.rawSha256=digest(a.bytes);assert.throws(()=>adapt(a));}
  const a=archive();a.bytes=a.bytes.replace('<Trades/>','<Trades></Trades>');a.metadata.rawSha256=digest(a.bytes);assert.deepEqual(adapt(a).trades,[]);assert.equal(adapt(a).tradeCoverageProven,false);
});
test('R7 order label derives from accepted capture timestamps, never the injected display clock',async()=>{
  const r=await result({captureOptionalLive:async()=>({...live(),asOfHkt:'2026-10-09 23:59 HKT'})});assert.equal(r.model.orders.asOfHkt,'2026-10-09 13:00 HKT');
  const m=structuredClone(r.model);m.orders.asOfHkt='2026-10-09 23:59 HKT';assert.throws(()=>renderNightActionReport(m),/ORDER_TIME/);
});
test('R4 protected classifier/selector roundtrip accepts canonical EOD and enforces component, freshness and HTML binding',async()=>{
  const {classifySleepPublication}=await import('../../scripts/xuan-ib-sleep-priority.mjs');const {selectNewestCandidate}=await import('../../scripts/xuan-ib-promotion.mjs');
  const next=await result(),rich=await result({captureOptionalLive:async()=>live([order('BUY')])});
  const publication=classifySleepPublication(next.html),richPublication=classifySleepPublication(rich.html);assert.equal(publication.kind,'eod-action');
  const meta={schemaVersion:1,sourceSha:'c'.repeat(40),sourceCommitEpoch:1,dataDate:'2026-10-09',htmlBlob:richPublication.action.htmlBlob};
  const candidate={ref:'origin/codex/xuan-ib-synthetic-eod',sha:'d'.repeat(40),htmlBlob:publication.action.htmlBlob,dataDate:'2026-10-09',commitEpoch:3,publication};
  assert.equal(selectNewestCandidate([candidate],meta,richPublication),null);
  const weakMeta={...meta,htmlBlob:publication.action.htmlBlob};const richer={...candidate,htmlBlob:richPublication.action.htmlBlob,publication:richPublication};assert.equal(selectNewestCandidate([richer],weakMeta,publication),richer);
  for(const edit of [c=>delete c.publication.action,c=>c.publication.action.htmlBlob='f'.repeat(40),c=>c.publication.action.schemaVersion=5]){const c=structuredClone(candidate);edit(c);assert.throws(()=>selectNewestCandidate([c],meta,richPublication));}
  assert.throws(()=>classifySleepPublication(next.html+'modified'),/MODIFIED_HTML/);
  const nextDayMeta={...weakMeta,dataDate:'2026-10-08'};const nextDayState={kind:'other',dataDate:'2026-10-08',priorityKey:null,eligibleAtEpoch:null};const laterWeak={...candidate,commitEpoch:99};assert.equal(selectNewestCandidate([richer,laterWeak],nextDayMeta,nextDayState),richer);
  const stale=structuredClone(richer);stale.publication.action.readAtEpoch--;assert.equal(selectNewestCandidate([stale],weakMeta,publication),null);
  const oldLegacy=structuredClone(rich.model);oldLegacy.schemaVersion=5;oldLegacy.status='partial';oldLegacy.cash.status='ready';oldLegacy.notes=[];const legacyState=classifySleepPublication(renderNightActionReport(oldLegacy));assert.equal(selectNewestCandidate([candidate],{...meta,htmlBlob:legacyState.action.htmlBlob},legacyState),null);
});

test('public trend dates/ages and invalid header clocks cannot carry arbitrary diagnostic text',async()=>{
  const r=await result({captureOptionalLive:async()=>live([order('BUY')])});
  for(const edit of [m=>m.orders.buys[0].trend.firstDate='SYNTHETIC_PRIVATE_PATH',m=>m.orders.buys[0].trend.ageDays='SYNTHETIC_ACCOUNT',m=>m.asOfHkt='2026-10-09 99:99 HKT · 数据至 2026-10-08']){const m=structuredClone(r.model);edit(m);assert.throws(()=>renderNightActionReport(m));}
});
test('R2N1 excessive order count and unsupported SELL description degrade only optional orders, never the four-card report',async()=>{
  const many=Array.from({length:61},(_,i)=>({...order('BUY'),order_id:i+1}));
  const unsupported={...order('SELL'),primary_description:'Sell 2 Synthetic unsupported description'};
  for(const rows of [many,[unsupported]]){const r=await result({captureOptionalLive:async()=>live(rows)});assert.equal(r.model.orders.status,'unknown');assert.equal(r.model.orders.reason,'ORDERS_MALFORMED_OR_UNMATCHED');assert.equal(r.model.sourceOutcomes[3].status,'malformed');assert.equal(r.model.orders.buys,null);assert.equal(r.model.orders.sells,null);assert.equal(r.model.cash.orderReserve,null);assert.equal(r.model.cash.planning,null);assert.equal(r.model.allocation.projectedTotal,null);assert.equal(r.model.cash.ib,200);assert.equal(r.model.cash.noah,50);assert.equal(r.model.allocation.status,'ready');assert.equal(r.model.allocation.categories.length,4);assert.equal(validateNightActionHtml(r.html,'2026-10-09').orderCount,null);for(const title of ['本轮补仓','挂单提醒','现金优先补仓参考','股票四类配置'])assert.ok(r.html.includes(title));}
  const accepted=await result({captureOptionalLive:async()=>live(many.slice(0,60))});assert.equal(accepted.model.orders.buys.length,60);assert.equal(accepted.model.cash.orderReserve,1200);
});
test('R2N2 supplier financial metadata cannot enable coverage, reconciliation or a budget with the same raw source and identity proof',async()=>{
  const baseline=archive({residual:null}),tampered=structuredClone(baseline);Object.assign(tampered.metadata,{cashReconciliationResidual:0,executionsCoveredThrough:DATE,cancellationsVerified:true});
  assert.equal(baseline.bytes,tampered.bytes);assert.equal(baseline.metadata.rawSha256,tampered.metadata.rawSha256);
  for(const a of [baseline,tampered]){const parsed=adapt(a);assert.equal(parsed.tradeCoverageProven,false);assert.equal(parsed.reconciliation.status,'unknown');assert.equal(parsed.reconciliation.cashResidual,null);for(const verifier of [null,async()=>({status:'archive-verified'}),financialOracle({cashResidual:null,cashCoveredThrough:null,executionsCoveredThrough:null,cancellationsComplete:false,cashMovementsComplete:false})]){const r=await result({readArchive:async()=>a,verifyArchiveFinancial:verifier,captureOptionalLive:async()=>live()});assert.equal(r.model.reconciliation.status,'unknown');assert.equal(r.model.reconciliation.cashResidual,null);assert.equal(r.model.cash.planning,null);assert.equal(r.model.replenishment.status,'unavailable');assert.equal(r.model.cash.ib,200);assert.equal(r.model.allocation.status,'ready');}}
  const independent=await result({readArchive:async()=>baseline,verifyArchiveFinancial:financialOracle(),captureOptionalLive:async()=>live()});assert.equal(independent.model.reconciliation.status,'verified');assert.equal(independent.model.cash.planning,225);
  const pendingOracle=financialOracle({cashResidual:7,cashCoveredThrough:DATE,executionsCoveredThrough:DATE,cancellationsComplete:true,cashMovementsComplete:true});
  for(const a of [baseline,tampered]){const r=await result({readArchive:async()=>a,verifyArchiveFinancial:pendingOracle,captureOptionalLive:async()=>live()});assert.equal(r.model.reconciliation.status,'pending');assert.equal(r.model.reconciliation.cashResidual,7);assert.equal(r.model.cash.planning,null);}
});
test('independent financial proof binds receipt/snapshot evidence plus source hash, generation, account, query and cutoff',async()=>{
  const fixed=await financialOracle()({archive:archive()});
  for(const edit of [p=>p.account='SYNTHETIC_OTHER',p=>p.rawSha256='f'.repeat(64),p=>p.generation='2',p=>p.sourceDate='2026-10-07',p=>p.configuredQueryId='SYNTHETIC_OTHER_QUERY',p=>delete p.evidence,p=>p.evidence.receiptSha256='invalid',p=>p.evidence.snapshotGeneration='',p=>p.facts.cashResidual=.004]){const proof=structuredClone(fixed);edit(proof);const r=await result({verifyArchiveFinancial:async()=>proof,captureOptionalLive:async()=>live()});assert.equal(r.model.cash.planning,null);assert.equal(r.model.cash.ib,200);assert.equal(r.model.allocation.status,'ready');}
  const r=await result({captureOptionalLive:async()=>live()});assert.equal(r.model.reconciliation.verificationSha256,digest(fixed));assert.equal(r.model.cash.planning,225);assert.equal(r.model.cash.planningBasis.status,'conditional');const stored=r.objects.get(r.receipt.sources.find(s=>s.sourceKey==='ib.flexEod').privateObject);assert.deepEqual(stored.financialProof,fixed);assert.ok(!JSON.stringify(r.model).includes(ACCOUNT));
  const m=structuredClone(r.model);m.reconciliation.verificationSha256=null;assert.throws(()=>renderNightActionReport(m),/FINANCIAL_PROOF/);
});

test('R3N1 every optional-derived boundary degrades orders while preserving independently valid core cards',async()=>{
  const largeArchive=archive();largeArchive.bytes=largeArchive.bytes.replace('endingCash="200"','endingCash="600000000000"');largeArchive.metadata.rawSha256=digest(largeArchive.bytes);
  // Separate fixed synthetic oracle for this predeclared large-balance archive;
  // it never copies facts or financial metadata from the adapter input.
  const largeProof=await financialOracle()({archive:archive()});largeProof.rawSha256=digest(largeArchive.bytes);
  const largeSnapshot=async({sourceKey})=>{const s=snapshot(sourceKey);if(sourceKey==='sharesight.ibGroupedPerformance')s.raw.data.report.holdings[5].value=600e9;return s;};
  const fractionalSnapshot=async({sourceKey})=>{const s=snapshot(sourceKey);if(sourceKey==='sharesight.ibGroupedPerformance')s.raw.data.report.holdings[3].value=180.004;return s;};
  const projectedOverflow=async({sourceKey})=>{const s=snapshot(sourceKey);if(sourceKey==='sharesight.ibGroupedPerformance')for(const row of s.raw.data.report.holdings.slice(0,5))row.value*=900e6;return s;};
  const filled={...order('BUY'),cum_shares_qty:'2',remaining_shares_qty:'0'};
  const cases=[
    {captureOptionalLive:async()=>live([order('BUY','1000000000000')])},
    {verifyArchiveFinancial:null,captureOptionalLive:async()=>live([order('BUY','1000000000000')])},
    {snapshotReader:fractionalSnapshot,captureOptionalLive:async()=>live([filled])},
    {readArchive:async()=>largeArchive,verifyArchiveFinancial:async()=>structuredClone(largeProof),snapshotReader:largeSnapshot,captureOptionalLive:async()=>live()},
    {snapshotReader:projectedOverflow,captureOptionalLive:async()=>live([order('BUY','20000000000')])},
  ];
  for(const options of cases){
    const base=await result({...options,captureOptionalLive:null}),r=await result(options);
    assert.equal(r.model.orders.status,'unknown');assert.equal(r.model.orders.reason,'ORDERS_MALFORMED_OR_UNMATCHED');assert.equal(r.model.sourceOutcomes[3].status,'malformed');
    for(const key of ['orderReserve','planning','totalCapacity'])assert.equal(r.model.cash[key],null);
    assert.equal(r.model.allocation.projectedTotal,null);assert.equal(r.model.replenishment.status,'unavailable');
    for(const key of ['ib','noah','pool','reserve','callApplied','cashLike','eod'])assert.deepEqual(r.model.cash[key],base.model.cash[key]);
    assert.deepEqual(r.model.allocation,base.model.allocation);assert.deepEqual(r.model.reconciliation,base.model.reconciliation);
    assert.equal(validateNightActionHtml(r.html,'2026-10-09').orderCount,null);
    for(const title of ['本轮补仓','挂单提醒','现金优先补仓参考','股票四类配置'])assert.ok(r.html.includes(title));
  }
});
test('R3N1 supported empty and 60-order derived models keep original conditional planning; core failures still escape',async()=>{
  const empty=await result({captureOptionalLive:async()=>live()});assert.equal(empty.model.orders.status,'ready');assert.equal(empty.model.cash.planning,225);assert.equal(empty.model.cash.totalCapacity,315);assert.equal(empty.model.allocation.projectedTotal,1000);
  const rows=Array.from({length:60},(_,i)=>({...order('BUY'),order_id:i+1}));const sixty=await result({captureOptionalLive:async()=>live(rows)});assert.equal(sixty.model.orders.buys.length,60);assert.equal(sixty.model.cash.orderReserve,1200);assert.equal(sixty.model.allocation.projectedTotal,2200);
  const badArchive=archive();badArchive.bytes=badArchive.bytes.replace('endingCash="200"','endingCash="10000000000000"');badArchive.metadata.rawSha256=digest(badArchive.bytes);
  for(const captureOptionalLive of [null,async()=>live(),async()=>live([order('BUY','1000000000000')])]){const h=harness({readArchive:async()=>badArchive,captureOptionalLive});await assert.rejects(runPrivateEodReport(h.options));assert.equal(h.objects.size,0);}
  const {buildEodActionModel}=await import('../../scripts/xuan-ib-eod-action-model.mjs');
  assert.throws(()=>buildEodActionModel({dataDate:'2026-10-09',sourceDate:DATE,asOfHkt:empty.model.asOfHkt,flex:adapt(archive()),snapshots:[],live:live(),reserve:1e13,sourceOutcomes:empty.model.sourceOutcomes}),/EOD_MODEL_INPUT/);
});

test('R4N1 same-cutoff independent financial evidence survives publisher initial/final context and canonical selection with unknown orders',async()=>{
  const {classifySleepPublication}=await import('../../scripts/xuan-ib-sleep-priority.mjs');const {selectNewestCandidate}=await import('../../scripts/xuan-ib-promotion.mjs');
  const verified=await result(),unknown=await result({verifyArchiveFinancial:null}),peer=await result();
  assert.equal(verified.model.orders.status,'unknown');assert.equal(unknown.model.orders.status,'unknown');assert.equal(verified.model.reconciliation.status,'verified');assert.equal(unknown.model.reconciliation.status,'unknown');
  const publication=classifySleepPublication(unknown.html),oldState=classifySleepPublication(verified.html),peerState=classifySleepPublication(peer.html);
  assert.equal(publication.action.components,oldState.action.components);assert.equal(publication.action.financialProofSha256,null);assert.equal(oldState.action.financialProofSha256,verified.model.reconciliation.verificationSha256);
  const meta={schemaVersion:1,sourceSha:'c'.repeat(40),sourceCommitEpoch:1,dataDate:'2026-10-09',htmlBlob:oldState.action.htmlBlob};
  const candidate=(state,epoch=3)=>({ref:'origin/codex/xuan-ib-synthetic-evidence',sha:'d'.repeat(40),htmlBlob:state.action.htmlBlob,dataDate:'2026-10-09',commitEpoch:epoch,publication:state});
  assert.equal(selectNewestCandidate([candidate(publication)],meta,oldState),null);
  assert.deepEqual(selectNewestCandidate([candidate(peerState)],meta,oldState),candidate(peerState));
  const weakMeta={...meta,htmlBlob:publication.action.htmlBlob};assert.deepEqual(selectNewestCandidate([candidate(oldState)],weakMeta,publication),candidate(oldState));
  const previousDate={...weakMeta,dataDate:'2026-10-08'},previousState={kind:'other',dataDate:'2026-10-08',priorityKey:null,eligibleAtEpoch:null};assert.equal(selectNewestCandidate([candidate(publication,99),candidate(oldState)],previousDate,previousState).publication.action.reconciliationStatus,'verified');
  const laterWeak=await result({verifyArchiveFinancial:null,now:()=>NOW()+60000}),laterWeakState=classifySleepPublication(laterWeak.html);assert.ok(laterWeakState.action.readAtEpoch>oldState.action.readAtEpoch);assert.equal(selectNewestCandidate([candidate(laterWeakState,99),candidate(oldState)],previousDate,previousState).publication.action.reconciliationStatus,'verified');
  for(const late of [false,true]){let calls=0,reads=0;await assert.rejects(publishPrepared({html:unknown.html,receipt:unknown.receipt,now:NOW,loadContext:async()=>({...unknown.c,previousHtml:!late||++reads>1?verified.html:''}),request:async p=>{calls++;if(p.query.startsWith('query'))return {data:{viewer:{login:'huanwujoy-crypto'},repository:{id:'synthetic',ref:{target:{oid:'a'.repeat(40)}}}}};return {data:{createRef:{ref:{name:p.variables.input.name,target:{oid:'a'.repeat(40)}}}}};}}),/COMPLETE_REPORT_EXISTS/);assert.equal(calls,late?2:0);}
  let calls=0;await publishPrepared({html:peer.html,receipt:peer.receipt,now:NOW,loadContext:async()=>({...peer.c,previousHtml:verified.html}),request:async p=>{calls++;if(p.query.startsWith('query'))return {data:{viewer:{login:'huanwujoy-crypto'},repository:{id:'synthetic',ref:{target:{oid:'a'.repeat(40)}}}}};if(p.query.includes('CreateRef'))return {data:{createRef:{ref:{name:p.variables.input.name,target:{oid:'a'.repeat(40)}}}}};return {data:{createCommitOnBranch:{commit:{oid:'d'.repeat(40)},ref:{name:p.variables.input.branch.branchName}}}};}});assert.equal(calls,3);
});
test('R4N1 pending proof is conservative at unchanged cutoff; newer cutoff and original complete schema5 remain eligible',async()=>{
  const {classifySleepPublication,canReplaceActionModel}=await import('../../scripts/xuan-ib-sleep-priority.mjs');const {selectNewestCandidate}=await import('../../scripts/xuan-ib-promotion.mjs');
  const verified=await result(),pending=await result({verifyArchiveFinancial:financialOracle({cashResidual:7,cashCoveredThrough:DATE,executionsCoveredThrough:DATE,cancellationsComplete:true,cashMovementsComplete:true})}),unknown=await result({verifyArchiveFinancial:null});
  assert.equal(pending.model.reconciliation.status,'pending');assert.notEqual(pending.model.reconciliation.verificationSha256,verified.model.reconciliation.verificationSha256);assert.equal(canReplaceActionModel(pending.model,verified.model),false);assert.equal(canReplaceActionModel(pending.model,unknown.model),true);assert.equal(canReplaceActionModel(unknown.model,pending.model),false);
  const pendingPeer=await result({verifyArchiveFinancial:financialOracle({cashResidual:8,cashCoveredThrough:DATE,executionsCoveredThrough:DATE,cancellationsComplete:true,cashMovementsComplete:true})});assert.equal(canReplaceActionModel(pendingPeer.model,pending.model),true);
  const old=structuredClone(verified.model);old.sourceDate='2026-10-07';old.asOfHkt=old.asOfHkt.replace(DATE,old.sourceDate);old.provenance.flex.sourceDate=old.sourceDate;old.provenance.flex.coveredThrough=old.sourceDate;for(const s of old.provenance.sharesight)s.sourceDate=old.sourceDate;old.notes[0]=old.notes[0].replace(DATE,old.sourceDate);
  const oldState=classifySleepPublication(renderNightActionReport(old)),nextState=classifySleepPublication(unknown.html);assert.equal(canReplaceActionModel(unknown.model,old),true);
  const meta={schemaVersion:1,sourceSha:'c'.repeat(40),sourceCommitEpoch:1,dataDate:'2026-10-09',htmlBlob:oldState.action.htmlBlob};const candidate=state=>({ref:'origin/codex/xuan-ib-synthetic-evidence',sha:'d'.repeat(40),htmlBlob:state.action.htmlBlob,dataDate:'2026-10-09',commitEpoch:3,publication:state});assert.deepEqual(selectNewestCandidate([candidate(nextState)],meta,oldState),candidate(nextState));
  const full=structuredClone((await result({captureOptionalLive:async()=>live()})).model);full.schemaVersion=5;full.status='ready';full.cash.status='ready';full.notes=[];const fullState=classifySleepPublication(renderNightActionReport(full)),verifiedState=classifySleepPublication(verified.html);assert.equal(fullState.kind,'complete-pm');assert.equal(Object.hasOwn(fullState.action,'financialProofSha256'),false);assert.equal(canReplaceActionModel(full,verified.model),true);assert.deepEqual(selectNewestCandidate([candidate(fullState)],{...meta,htmlBlob:verifiedState.action.htmlBlob},verifiedState),candidate(fullState));
});
