// Prepare actual selected report fields from private original bytes. No calls,
// refresh, trade/ledger writes or publication. All identifiers remain private.
import crypto from 'node:crypto';import {fingerprint,APPROVED_IB_ACCOUNT_ID} from '../../scripts/xuan-ib-run-manifest.mjs';
import {createAssociationReceipt,validateAssociationSnapshot} from '../../scripts/xuan-ib-account-association.mjs';
import {planPreopen} from './calendar.mjs';
import {normalizePositions} from '../../scripts/xuan-ib-source-adapter.mjs';import {adaptTradeConfirmationCsv} from './trade_confirmation.mjs';import {renderIntradayUpdate} from '../../scripts/xuan-ib-intraday-update.mjs';
const KEYS=['ib.accountSummary','ib.positions','ib.orders','ib.balances','ib.trades'],hash=b=>crypto.createHash('sha256').update(b).digest('hex'),fail=()=>{throw Error('INTRADAY_EVIDENCE_INVALID');};
const numeric=v=>{if((typeof v!=='number'&&typeof v!=='string')||v===''||!Number.isFinite(Number(v))||Math.abs(Number(v))>1e12)fail();return Number(v);};
const currency=v=>typeof v==='string'&&/^[A-Z]{3}$/.test(v);
const symbol=o=>{const q=numeric(o.total_shares_qty),m=/^(?:Buy|Sell)\s+(\d+(?:\.\d+)?)\s+([A-Z][A-Z0-9./ -]{0,20})$/.exec(o.primary_description||'');return m&&Number(m[1])===q?m[2]:(o.primary_description||'');};
const isoDay=t=>typeof t==='string'&&/T.*(?:Z|[+-]\d{2}:\d{2})$/.test(t)&&Number.isFinite(Date.parse(t))?new Intl.DateTimeFormat('en-CA',{timeZone:'America/New_York',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(t)):null;
export function prepareIntradayUpdate({capture,sourceBytes,tradeCsv,expectedTradeHash,orderDetailBytes=null,context,now=Date.now()}){
 if(capture?.status!=='captured'||capture.mode!=='read_only'||capture.publication!=='none'||capture.sourceCount!==5||capture.sources?.length!==5)fail();
 const start=Date.parse(capture.startedAt),end=Date.parse(capture.completedAt);if(!Number.isFinite(start)||!Number.isFinite(end)||end<start||end>now||now-start>1800000||end-start>300000)fail();
 const dataDate=new Date(start+28800000).toISOString().slice(0,10),raw={},sources=[];
 for(const key of KEYS){const refs=capture.sources.filter(s=>s.sourceKey===key);if(refs.length!==1||!Buffer.isBuffer(sourceBytes[key])||hash(sourceBytes[key])!==refs[0].evidenceSha256)fail();const s=JSON.parse(sourceBytes[key]);if(s.sourceKey!==key||fingerprint(s.raw)!==refs[0].rawFingerprint||s.startedAt!==refs[0].startedAt||s.completedAt!==refs[0].completedAt||!Number.isFinite(Date.parse(s.startedAt))||!Number.isFinite(Date.parse(s.completedAt))||Date.parse(s.startedAt)<start||Date.parse(s.completedAt)>end||Date.parse(s.completedAt)<Date.parse(s.startedAt))fail();raw[key]=s.raw;sources.push({sourceKey:key,startedAt:s.startedAt,completedAt:s.completedAt});}
 if(typeof tradeCsv!=='string'||!/^[a-f0-9]{64}$/.test(expectedTradeHash)||hash(tradeCsv)!==expectedTradeHash)fail();
 // The target is supplied by the trusted prior completed NYSE session, not
 // guessed from file mtime or all of the CSV's date-like cells.
 const target=context.targetTradeDate;if(!target||target>=dataDate||target!==planPreopen(start).sourceDate)fail();
 const tc=adaptTradeConfirmationCsv(tradeCsv,{expectedAccount:APPROVED_IB_ACCOUNT_ID,targetTradeDate:target});if(!tc.accountScope.rowsMatchApprovedAccount||tc.duplicateRows||!tc.executions.length)fail();
 const positions=normalizePositions(raw['ib.positions']);if(positions.some(p=>p.contractId===null)||new Set(positions.map(p=>p.contractId)).size!==positions.length)fail();
 const balances=raw['ib.balances'].balances;if(!Array.isArray(balances)||!balances.length||new Set(balances.map(r=>r.currency)).size!==balances.length)fail();
 const base=balances.find(r=>r.currency==='BASE');if(base&&numeric(base.exchange_rate)!==1)fail();
 const cash=balances.filter(r=>r.currency!=='BASE').map(r=>{if(!currency(r.currency)||numeric(r.exchange_rate)<=0)fail();return{currency:r.currency,cashBalance:numeric(r.cash_balance),settledCash:numeric(r.settled_cash),exchangeRate:numeric(r.exchange_rate)};});
 const trades=raw['ib.trades'].trades;if(!Array.isArray(trades)||trades.length>1000||new Set(trades.map(r=>r.trade_id)).size!==trades.length||trades.some(r=>typeof r.trade_id!=='string'||!r.trade_id||!Number.isSafeInteger(r.order_id)||!currency(r.currency)||!['BUY','SELL'].includes(r.side)||typeof r.trade_time!=='string'||!r.trade_time))fail();
 const detail=orderDetailBytes?JSON.parse(orderDetailBytes):null;if(detail&&(!Buffer.isBuffer(orderDetailBytes)||detail.source!=='ib-read-only-order-details'||detail.accountId!==APPROVED_IB_ACCOUNT_ID||!Array.isArray(detail.orders)||new Set(detail.orders.map(d=>d.order_id)).size!==detail.orders.length||!Number.isFinite(Date.parse(detail.checkedAt))||Date.parse(detail.checkedAt)>now||now-Date.parse(detail.checkedAt)>1800000))fail();
 const orders=raw['ib.orders'].orders;if(!Array.isArray(orders)||orders.length>60||new Set(orders.map(r=>r.order_id)).size!==orders.length)fail();
 const displayedOrders=orders.map(o=>{if(!Number.isSafeInteger(o.order_id)||!['BUY','SELL'].includes(o.side))fail();const total=numeric(o.total_shares_qty),remaining=numeric(o.remaining_shares_qty),filled=numeric(o.cum_shares_qty),limit=numeric(o.limit_price);if(total<=0||remaining<0||filled<0||limit<=0||Math.abs(total-remaining-filled)>1e-8)fail();const name=symbol(o);let curr=null,basis='unresolved';if(currency(o.currency)){curr=o.currency;basis='source';}else{const same=trades.filter(t=>t.order_id===o.order_id&&t.symbol===name&&t.side===o.side),set=new Set(same.map(t=>t.currency));if(same.length&&set.size===1){curr=same[0].currency;basis='same-order-execution';}else if(detail){const ds=detail.orders.filter(d=>d.order_id===o.order_id);if(ds.length===1&&currency(ds[0].currency)){const p=positions.find(p=>p.contractId===String(ds[0].contract_id));if(!p||p.currency!==ds[0].currency)fail();curr=ds[0].currency;basis='same-contract-detail';}}}return{description:name,side:o.side,quantity:remaining,limit,currency:curr,status:o.order_status,currencyEvidence:basis};});
 const known=tc.executions.filter(e=>e.reportedTradeDate===target);if(!known.length)fail();
 const grouped=new Map();for(const e of known){const key=e.orderId+'|'+e.symbol+'|'+e.side+'|'+e.currency;const g=grouped.get(key)||{quantity:0,amount:0};g.quantity+=Math.abs(e.economics.Quantity);g.amount+=Math.abs(e.economics.Quantity)*e.economics.Price;grouped.set(key,g);}
 const exactExecutions=known.every(e=>{const ts=trades.filter(t=>t.trade_id===e.executionId);return ts.length===1&&ts[0].symbol===e.symbol&&ts[0].side===e.side&&ts[0].currency===e.currency&&isoDay(ts[0].trade_time)===target&&Math.abs(Math.abs(numeric(ts[0].size))-Math.abs(e.economics.Quantity))<1e-8&&Math.abs(numeric(ts[0].price)-e.economics.Price)<1e-8&&Math.abs(Math.abs(numeric(ts[0].commission))-Math.abs(e.economics.Commission))<0.000001;});
 let matched=true;for(const [key,g]of grouped){const [id,name,side,curr]=key.split('|'),ts=trades.filter(t=>String(t.order_id)===id&&t.symbol===name&&t.side===side&&t.currency===curr&&isoDay(t.trade_time)===target);const q=ts.reduce((n,t)=>n+Math.abs(numeric(t.size)),0),amount=ts.reduce((n,t)=>n+Math.abs(numeric(t.size))*numeric(t.price),0);if(Math.abs(q-g.quantity)>1e-8||Math.abs(amount-g.amount)>Math.max(0.01,Math.abs(g.amount)*1e-8))matched=false;}
 matched=exactExecutions||matched;
 const summary=raw['ib.accountSummary'];if(!currency(summary.currency))fail();const converted=cash.reduce((sum,r)=>sum+r.cashBalance*r.exchangeRate,0),cashCrossCheck=(!base||Math.abs(numeric(base.cash_balance)-numeric(summary.total_cash_value))<=0.05)&&cash.some(r=>r.currency===summary.currency&&Math.abs(r.exchangeRate-1)<1e-9)&&Math.abs(converted-numeric(summary.total_cash_value))<=Math.max(0.05,Math.abs(converted)*1e-6)?'base-cash-cross-checked':'not-reconciled';
 validateAssociationSnapshot(context.association,{now,edition:'am'});const association=createAssociationReceipt(context.association,{now,edition:'am',previousSourceSha:context.previousSourceSha,runId:hash(crypto.randomUUID())});
 const evidenceSha256=fingerprint({capture,tradeHash:tc.rawSha256,orderDetailsHash:orderDetailBytes?hash(orderDetailBytes):null}),model={schemaVersion:8,status:'partial',dataDate,asOfHkt:new Date(start+28800000).toISOString().slice(0,16).replace('T',' ')+' HKT',sourceDate:target,captureStartedAt:capture.startedAt,captureCompletedAt:capture.completedAt,sources,positions:positions.map(p=>({description:p.description,quantity:p.quantity,price:p.price,marketValue:p.marketValueNative,currency:p.currency})),orders:displayedOrders,balances:cash,recentTrades:trades.map(t=>({symbol:t.symbol,side:t.side,quantity:Math.abs(numeric(t.size)),price:numeric(t.price),currency:t.currency,time:t.trade_time,date:isoDay(t.trade_time),commission:numeric(t.commission),commissionCurrency:null})),knownExecutions:known.map(e=>({symbol:e.symbol,side:e.side,quantity:Math.abs(e.economics.Quantity),price:e.economics.Price,currency:e.currency,time:e.executedLocalDate+' '+e.executedLocalTime+'（源时区未声明）',date:e.reportedTradeDate,commission:e.economics.Commission,commissionCurrency:e.commissionCurrency})),targetMatch:matched?'matched-known-executions':'conflict-or-unmatched',cashCrossCheck,evidenceSha256,association,expiresAt:context.association.policy.expiresAt,previousDataDate:context.previousMeta.dataDate,previousReportSha:context.previousSourceSha,previousSourceSha:context.previousSourceSha,recommendations:'not-issued'};
 const html=renderIntradayUpdate(model),receipt={schemaVersion:1,mode:'private_intraday_update',status:'partial',dataDate,sourceDate:target,startedAt:capture.startedAt,completedAt:capture.completedAt,sourceCount:5,sources:capture.sources.map(s=>({sourceKey:s.sourceKey,sha256:s.evidenceSha256})),association,evidenceSha256,artifact:{sha256:hash(html)},publication:'none'};
 return{model,html,receipt};
}
