import test from 'node:test';import assert from 'node:assert/strict';import crypto from 'node:crypto';
import {prepareLimitedReadback} from './limited_report.mjs';import {publishPrepared} from './publish.mjs';
import {associationPolicyBlob} from '../../scripts/xuan-ib-account-association.mjs';import {fingerprint} from '../../scripts/xuan-ib-run-manifest.mjs';
import {renderLimitedStatus} from '../../scripts/xuan-ib-limited-status.mjs';import {validateNightActionHtml} from '../../scripts/xuan-ib-night-action-guard.mjs';
import {classifySleepPublication} from '../../scripts/xuan-ib-sleep-priority.mjs';import {classifyEdition,extractPrimaryDateLine} from '../../scripts/xuan-ib-publish-health.mjs';
import fs from 'node:fs';import vm from 'node:vm';
import {collectLimitedDelivery} from './limited_delivery.mjs';
const now=Date.parse('2026-10-02T07:10:00Z'),hash=x=>crypto.createHash('sha256').update(x).digest('hex');
function fixture(){
 const policy={schemaVersion:1,policyId:'ib-primary-7day-pilot-v1',accountAlias:'IB-HK',basis:'owner-attested-recurring-v1',status:'active',purpose:'xuan-ib-read-only-report',editions:['adhoc','am','pm'],publisher:'codex-verified-candidate-v1',validFrom:'2026-09-11T13:30:00.000Z',expiresAt:'2026-10-10T13:30:00.000Z'};
 const context={association:{policy,policyCommit:'a'.repeat(40),policyBlob:associationPolicyBlob(policy),checkedAt:new Date(now).toISOString()},previousMeta:{dataDate:'2026-10-01'},previousSourceSha:'c'.repeat(40),previousHtml:'old'};
 const capture={status:'captured',mode:'read_only',publication:'none',sourceCount:3,startedAt:'2026-10-02T07:06:00Z',completedAt:'2026-10-02T07:07:00Z',sources:[]},sourceBytes={};
 for(const [sourceKey,raw] of [['ib.accountSummary',{currency:'SYN'}],['ib.positions',{positions:[{contract_id:123}]}],['ib.orders',{orders:[{order_id:456}]}]]){const s={sourceKey,raw,startedAt:capture.startedAt,completedAt:capture.completedAt,rawFingerprint:fingerprint(raw)};const b=Buffer.from(JSON.stringify(s));sourceBytes[sourceKey]=b;capture.sources.push({sourceKey,startedAt:s.startedAt,completedAt:s.completedAt,rawFingerprint:s.rawFingerprint,evidenceSha256:hash(b)});}
 const trade={rawSha256:'f'.repeat(64),tradeDate:'2026-10-01',allRowsAccountMatchConfiguredIB:true,executions:6,orders:5,uniqueExecIDs:6,duplicate:0,conflict:0,matchSavedSharesight:true,cancelCorrectionCoverage:'unknown'};
 return{capture,sourceBytes,trade,cashRecovery:{auditMatched:true,independentSourceVerified:false},context,now};
}
test('verified independent existing capture builds honest partial page without values or schedule completion',()=>{const f=fixture(),r=prepareLimitedReadback(f);assert.deepEqual(validateNightActionHtml(r.html,'2026-10-02',{snapshot:f.context.association,previousSourceSha:f.context.previousSourceSha,now}),{dataDate:'2026-10-02',status:'partial',orderCount:0});assert.equal(classifySleepPublication(r.html).kind,'limited-readback');assert.equal(classifyEdition(extractPrimaryDateLine(r.html)),'adhoc');assert.match(r.html,/上一份报告原日期：2026-10-01/);assert.match(r.html,/现金恢复对账已吻合/);assert.match(r.html,/不计为定时盘前完成/);assert.ok(!r.html.includes('<script'));assert.ok(!r.html.includes('SYN'));assert.ok(!r.html.includes('contract_id'));});
test('modified raw, duplicate source, wrong trade identity/date and expired capture stop before rendering',()=>{for(const change of [f=>f.sourceBytes['ib.orders']=Buffer.from('{}'),f=>f.capture.sources[1]=f.capture.sources[0],f=>f.trade.allRowsAccountMatchConfiguredIB=false,f=>f.trade.tradeDate='2026-10-02',f=>f.trade.uniqueExecIDs=5,f=>f.now+=1800001]){const f=fixture();change(f);assert.throws(()=>prepareLimitedReadback(f),/LIMITED_EVIDENCE_INVALID/);}});
test('canonical guard rejects monetary fields, receipt time relabeling, wrong prior source and stale evidence',()=>{const f=fixture(),r=prepareLimitedReadback(f);for(const change of [m=>m.cash=100,m=>m.status='ready',m=>m.asOfHkt='2026-10-02 14:00 HKT']){const m=structuredClone(r.model);change(m);assert.throws(()=>renderLimitedStatus(m));}assert.throws(()=>validateNightActionHtml(r.html,'2026-10-02',{snapshot:f.context.association,previousSourceSha:'e'.repeat(40),now}));assert.throws(()=>validateNightActionHtml(r.html,'2026-10-02',{snapshot:f.context.association,previousSourceSha:f.context.previousSourceSha,now:now+1800001}),/STALE/);});
test('limited publisher uses exact signed one-file pipeline and independently rejects expired or changed evidence',async()=>{const f=fixture(),r=prepareLimitedReadback(f),calls=[];const request=async p=>{calls.push(p);if(p.query.startsWith('query'))return{data:{viewer:{login:'huanwujoy-crypto'},repository:{id:'repo',ref:{target:{oid:'a'.repeat(40)}}}}};if(p.query.includes('CreateRef'))return{data:{createRef:{ref:{name:p.variables.input.name,target:{oid:'a'.repeat(40)}}}}};return{data:{createCommitOnBranch:{commit:{oid:'d'.repeat(40)},ref:{name:p.variables.input.branch.branchName}}}};};const args={...r,request,loadContext:async()=>f.context,now:()=>now};assert.equal((await publishPrepared(args)).publication,'candidate-only');assert.deepEqual(calls[2].variables.input.fileChanges.additions.map(x=>x.path),['xuan-ib/index.html']);calls.length=0;await assert.rejects(publishPrepared({...args,receipt:{...r.receipt,evidenceSha256:'e'.repeat(64)}}));assert.equal(calls.length,0);await assert.rejects(publishPrepared({...args,now:()=>now+1800001}),/STALE/);assert.equal(calls.length,0);});
test('phone loader parses actual partial report as adhoc and never calls read clock data-asof',()=>{const r=prepareLimitedReadback(fixture()),loader=fs.readFileSync(new URL('../../xuan-ib/index.html',import.meta.url),'utf8');const infoCode=loader.slice(loader.indexOf('const reportInfo ='),loader.indexOf('const requireExactKeys ='));const info=vm.runInNewContext(infoCode+'reportInfo(html)',{html:r.html});assert.equal(info.edition,'临时补读');assert.equal(info.statusOnly,true);const statusCode=loader.slice(loader.indexOf('const statusFor ='),loader.indexOf('function updateDecisionControl'));const status=vm.runInNewContext(statusCode+'statusFor(record,"已检查")',{record:{info},clock:()=> '15:10'});assert.match(status,/数据部分核实/);assert.match(status,/读取 15:06/);assert.ok(!status.includes('数据至'));});
test('existing limited delivery only reads two fixed private objects and rejects stale/tampered/traversal',async()=>{const f=fixture(),r=prepareLimitedReadback(f),prefix=`delivery/2026-10-02/limited-readback-${r.model.evidenceSha256}/`,calls=[];const args={prefix,token:'synthetic-token',now:()=>now,loadContext:async()=>f.context,fetchImpl:async(url,options)=>{calls.push({url,options});return new Response(url.includes('receipt.json')?JSON.stringify(r.receipt):r.html);}};assert.equal((await collectLimitedDelivery(args)).outcome,'limited-readback');assert.equal(calls.length,2);assert.ok(calls.every(c=>c.url.startsWith('https://storage.googleapis.com/storage/v1/b/family-portfolio-gateway-xuan-preopen-private/o/delivery%2F2026-10-02%2F')));assert.ok(calls.every(c=>c.options.redirect==='error'&&!c.options.method));calls.length=0;await assert.rejects(collectLimitedDelivery({...args,prefix:'../report-check/private/'}));assert.equal(calls.length,0);await assert.rejects(collectLimitedDelivery({...args,now:()=>now+1800001}),/STALE/);await assert.rejects(collectLimitedDelivery({...args,fetchImpl:async()=>new Response('tampered')}));});
