import test from 'node:test';import assert from 'node:assert/strict';
import {prepareEarlyFeePlan,earlyFeeClockDecision} from './fee-early-publication-plan.mjs';
import {sha256} from './fee-completion-policy.mjs';
import {fixture as completionFixture} from './fee-completion-fixture.mjs';
const now=new Date('2026-10-03T03:20:00.000Z'),targetDate='2026-10-02',H='a'.repeat(64);
function options(){const pair=['schwab','webull'].map(broker=>{const receipt=completionFixture(broker);return {receipt,authenticatedProvider:receipt.issuer,receiptHash:sha256(JSON.stringify(receipt)),receiptGeneration:'1',pointerGeneration:'1'};});return {enabled:true,now,receiptMaxAgeMs:3600000,cashMaxAgeMs:300000,resolveTarget:async()=>({targetDate,targetTimezone:'America/New_York',lastCompletedSession:targetDate,calendarSha256:H}),readPair:async()=>structuredClone(pair),readDestination:async()=>({schwab:H,webull:H}),pair};}
const rehash=o=>o.pair.forEach(x=>x.receiptHash=sha256(JSON.stringify(x.receipt)));
test('default disabled makes no reads and cannot publish',async()=>{assert.deepEqual(await prepareEarlyFeePlan({readPair:()=>assert.fail('read')}),{state:'DISABLED'});});
test('verified pair can plan core before benchmarks; same target cache later plans replacement',async()=>{const o=options();const a=await prepareEarlyFeePlan(o);assert.equal(a.benchmarkState,'pending');assert.equal(a.sourceBenchmarkDate,null);assert.equal(a.activationAllowed,false);o.benchmarkCache={v:1,benchmarks:{spy:{series:[{d:targetDate,p:700,div:1}]},qqq:{series:[{d:targetDate,p:600}]}}};const b=await prepareEarlyFeePlan(o);assert.equal(b.benchmarkState,'session');assert.equal(b.benchmark.spyd,1);assert.equal(b.targetDate,a.targetDate);});
test('source target is independent from an old or partial benchmark cache',async()=>{const o=options();o.benchmarkCache={v:1,benchmarks:{spy:{series:[{d:'2026-10-01',p:700}]},qqq:{series:[{d:targetDate,p:600}]}}};const p=await prepareEarlyFeePlan(o);assert.equal(p.targetDate,targetDate);assert.equal(p.benchmark,null);});
test('report end date and stable destination never bypass pending SGOV or scan/fee/cash proof',async()=>{for(const mutate of [r=>r.pending.reviewRequired=1,r=>r.pending.metadataPending=1,r=>r.pending.unknownFee=1,r=>r.nontradeCoverage.unresolvedKnownItems=1,r=>r.sourceScan.paginationExhausted=false,r=>r.coveredScopeStatus='PARTIAL',r=>r.tradeProofs[0].actualFeeStatus='DEFAULT_ZERO',r=>r.cashProof.matchStatus='UNKNOWN',r=>r.targetDate='2026-10-01']){const o=options();mutate(o.pair[1].receipt);rehash(o);await assert.rejects(prepareEarlyFeePlan(o));}});
test('provider authentication, expiry and binding changes fail closed',async()=>{for(const mutate of [o=>o.pair[0].authenticatedProvider='local-json',o=>o.pair[0].receiptGeneration='',o=>o.pair[0].receipt.validUntil='2026-10-03T03:00:00.000Z',o=>o.readDestination=async()=>({schwab:'b'.repeat(64),webull:H})]){const o=options();mutate(o);rehash(o);await assert.rejects(prepareEarlyFeePlan(o));}const o=options();let n=0;const old=o.readPair;o.readPair=async()=>{const p=await old();if(n++)p[0].pointerGeneration='2';return p;};await assert.rejects(prepareEarlyFeePlan(o),/BINDING_CHANGED/);});
test('11:00 planning, 11:30 alert and replacement preserve no-duplicate decisions',()=>{const plan={state:'OFFLINE_PLAN_ONLY',benchmarkState:'session'};const at=s=>new Date('2026-10-03T'+s+':00.000Z');assert.equal(earlyFeeClockDecision({now:at('03:00')}),'wait_completion');assert.equal(earlyFeeClockDecision({now:at('03:30')}),'alert_completion_blocked');assert.equal(earlyFeeClockDecision({now:at('03:00'),plan}),'request_core_after_activation');assert.equal(earlyFeeClockDecision({now:at('03:00'),plan,corePublished:true}),'request_same_target_replacement_after_activation');for(const k of ['producerActive','candidatePending','publicationPending','leaseHeld','attemptUncertain'])assert.equal(earlyFeeClockDecision({now:at('03:00'),plan,[k]:true}),'wait_existing');});
test('already approved estimated cash option requires explicit selection and exact disclosure',async()=>{const o=options();o.pair[0].receipt.cashProof={targetDate,matchStatus:'NOT_INDEPENDENTLY_VERIFIED',currencyScope:['USD'],knownDifference:null,disclosure:'嘉信现金未独立核对'};rehash(o);await assert.rejects(prepareEarlyFeePlan(o),/INDEPENDENT_REQUIRED/);o.cashPolicy='allow-estimated-covered';const p=await prepareEarlyFeePlan(o);assert.equal(p.brokerCashDisclosure.message,'嘉信现金未独立核对');assert.equal(p.brokerCashDisclosure.schwabIndependentCashVerified,false);o.pair[1].receipt.pending.metadataPending=1;rehash(o);await assert.rejects(prepareEarlyFeePlan(o),/PENDING/);});
