import test from 'node:test';import assert from 'node:assert/strict';import crypto from 'node:crypto';
import {fixture,D,N,H} from './fee-completion-fixture.mjs';
import {prepareBinding} from './fee-completion-runtime.mjs';import {gcsReceiptReader} from './fee-completion-transport.mjs';
import {assertCompletionBeforePromotion,assertFeePublicReadback} from './fee-publish-readback.mjs';
const sha=b=>crypto.createHash('sha256').update(b).digest('hex');
async function setup(){const key=Buffer.alloc(32,3),dataBytes=Buffer.from('{"enc":true,"synthetic":true}'),env={FEE_BROKER_COMPLETENESS_ENABLED:'true'};
 const receipts=Object.fromEntries(['schwab','webull'].map(b=>[b,fixture(b)]));let generation='1';
 const read=async(b,k)=>{const raw=Buffer.from(JSON.stringify(receipts[b])),hash=sha(raw);return k.endsWith('current.json')?{generation,value:{schema:'fee.broker-completion-pointer.v2',broker:b,targetDate:D,state:'COMPLETE',receiptGeneration:'1',receiptHash:hash,receiptRef:`fee-completion/v2/${b}/${D}/receipts/${hash}.json`,destinationFingerprint:H}}:{generation:'1',raw,value:receipts[b]};};
 const readDestination=async()=>({schwab:H,webull:H}),health={schema:'fee-console.daily-health.v1',checkedAt:N,targetDate:D,sourceDates:{schwab:D,webull:D,benchmark:null},outcome:'updated',dataSha256:sha(dataBytes),errorCode:null};
 health.brokerSyncBinding=await prepareBinding({env,read,readDestination,targetDate:D,dataSha256:health.dataSha256,key,now:new Date(N)});
 return {health,dataBytes,key,read,readDestination,candidateSha:'b'.repeat(40),expectedTargetDate:D,now:new Date(N),env,changeGeneration(){generation='2';}};
}
test('fixed GCS completion transport blocks arbitrary broker/path before any network',async()=>{let calls=0;const read=gcsReceiptReader({token:'synthetic-test-token',fetchImpl:()=>{calls++;throw Error('unexpected');}});for(const [b,k] of [['ib','secret'],['webull','other/prefix'],['webull',`fee-completion/v2/schwab/${D}/current.json`]])await assert.rejects(read(b,k));assert.equal(calls,0);});
test('protected promotion guard revalidates encrypted exact data binding and live generations',async()=>{const o=await setup();assert.equal((await assertCompletionBeforePromotion(o)).state,'VERIFIED');o.changeGeneration();await assert.rejects(assertCompletionBeforePromotion(o),/BINDING_CHANGED/);});
test('disabled, wrong-target, ciphertext drift and public drift never bypass source gates',async()=>{for(const mutate of [o=>o.env={},o=>o.expectedTargetDate='2026-10-01',o=>o.dataBytes=Buffer.from('tampered'),o=>o.readDestination=async()=>({schwab:'c'.repeat(64),webull:H})]){const o=await setup();mutate(o);await assert.rejects(assertCompletionBeforePromotion(o));}const o=await setup();assert.equal(assertFeePublicReadback({mainHealth:o.health,publicHealth:o.health,mainBytes:o.dataBytes,publicBytes:o.dataBytes,targetDate:D}).benchmarkState,'pending');assert.throws(()=>assertFeePublicReadback({mainHealth:o.health,publicHealth:o.health,mainBytes:o.dataBytes,publicBytes:o.dataBytes,targetDate:D,benchmarkRequired:true}));assert.throws(()=>assertFeePublicReadback({mainHealth:o.health,publicHealth:o.health,mainBytes:o.dataBytes,publicBytes:Buffer.from('drift'),targetDate:D}));});
