import test from 'node:test';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {importHoldings} from './xuan-weekly-ishares-import.mjs';
function imported(rows,bindings=[]){const fields=['isin','ticker','issueName','holdingPercent','assetClass','currency'];const d=Object.fromEntries(fields.map(k=>[k,{value:rows.map(r=>r[k])}]));d.asOfDate={value:20261001};const raw=JSON.stringify({productId:264659,fundName:'iShares Core MSCI EM IMI UCITS ETF',componentsByNameMap:{holdings:{containersByNameMap:{all:{dataPointsByNameMap:d}}}}});return importHoldings(raw,{fund:'EIMI',productId:264659,asOf:'2026-10-01',sha256:createHash('sha256').update(raw).digest('hex'),bindings});}
const eq=(isin,name,weight,currency='USD')=>({isin,ticker:isin,issueName:name,holdingPercent:weight,assetClass:'Equity',currency});
test('same ISIN across trading currencies aggregates weight but preserves each currency row',()=>{const r=imported([eq('US0000000001','Issuer',40,'USD'),eq('US0000000001','Issuer',60,'EUR')]);assert.equal(r.holdings.length,1);assert.equal(r.holdings[0].weightMicroPercent,100000000);assert.deepEqual(r.holdings[0].sourceRows.map(x=>x.currency),['USD','EUR']);assert.deepEqual(r.audit.map(x=>x.currency),['USD','EUR']);});
test('ADR common preferred exact identifiers remain independent; names never bind fuzzily',()=>{const r=imported([eq('US0000000001','ADR',40),eq('US0000000002','Common',40),eq('US0000000003','Preferred',20)]);assert.equal(new Set(r.holdings.map(x=>x.issuerKey)).size,3);assert.throws(()=>imported([eq('US0000000001','ADR',100)],[{fund:'EIMI',isin:'US0000000001',name:'Common',target:{issuerKey:'issuer'}}]),/name_conflict/);});
test('both independently identified nested ETF structures refuse ordinary equity binding',()=>{for(const isin of ['DE000A0Q4R85','IE00BYYR0489']){const r=imported([eq(isin,'Nested fund',100)]);assert.equal(r.holdings[0].kind,'nested-etf');assert.equal(r.holdings[0].issuerKey,'unreviewed-isin-'+isin);assert.throws(()=>imported([eq(isin,'Nested fund',100)],[{fund:'EIMI',isin,name:'Nested fund',target:{issuerKey:'issuer'}}]),/nested_etf_binding_requires_underlying/);}});
test('signed negative cash is audited; positive-only over-allocation is rejected without normalization',()=>{assert.throws(()=>imported([eq('US0000000001','Issuer',101),{isin:null,ticker:'USD',issueName:'USD cash',holdingPercent:-1,assetClass:'Cash',currency:'USD'}]),/source_total_invalid/);});
test('missing source weight is rejected instead of silently converted to zero',()=>{assert.throws(()=>imported([eq('US0000000001','Issuer',100),eq('US0000000002','Missing',null)]),/row_invalid/);});
