import test from 'node:test';import assert from 'node:assert/strict';
import {DEFAULT_POLICY,buildAiExposure,renderAiExposure}from'./xuan-weekly-ai-exposure.mjs';
import {buildAiDualExposure,renderAiDualExposure}from'./xuan-weekly-ai-dual-exposure.mjs';
import {buildAiReviewPriority,renderAiReviewPriority} from './xuan-weekly-ai-review-priority.mjs';
const cutoff='2026-10-02';
function fixture(){const policy=structuredClone(DEFAULT_POLICY);policy.etfSnapshots=[{instrumentId:'9001',symbol:'SYNTH',fundName:'Synthetic target fund',basis:'economic-exposure',asOf:'2026-10-01',source:'https://example.org/qqq-holdings',evidenceKind:'proxy_estimated',actualCompositionVerified:false,sourceCompositionComplete:true,proxy:{fundName:'Invesco QQQ',symbol:'QQQ',benchmark:'Nasdaq-100',benchmarkSource:'https://example.org/benchmark',limitations:['Different fees, cash and rebalance timing; approximate trend only.']},holdings:[{issuerKey:'nvidia',weightBp:2000},{issuerKey:'proxy-still-unknown',weightBp:1000}]}];const envelope={riskDenominator:{components:[{key:'a',valueMicro:'100000000'},{key:'b',valueMicro:'50000000'},{key:'c',valueMicro:'0'}]},riskConstituents:[{instrumentId:'9001',symbol:'SYNTH',assetType:'ETF',portfolioId:'synthetic',custodian:'Synthetic',identityVerified:true,valueDate:cutoff,marketValueMicro:'100000000'}]};return{policy,envelope};}
const calc=(f,date=cutoff)=>buildAiExposure(f.envelope,{cutoff:date,policy:f.policy});
test('proxy uses actual fund value and NAV without normalizing partial proxy coverage',()=>{const f=fixture(),a=calc(f),r=a.rows[0];assert.equal(a.denominatorCents,'15000');assert.equal(a.cash.marketValueCents,'5000');assert.equal(r.marketValueCents,'10000');assert.equal(r.uncoveredCents,'8000');assert.equal(r.recordedBp,3000);assert.equal(r.unclassifiedBp,1000);assert.equal(r.unrecordedBp,7000);assert.equal(r.evidenceKind,'proxy_estimated');assert.equal(r.actualCompositionVerified,false);assert.equal(r.sourceCompositionComplete,false);assert.equal(a.coverageComplete,false);});
test('actual evidence rows remain distinct from proxy estimates',()=>{const f=fixture();delete f.policy.etfSnapshots[0].evidenceKind;delete f.policy.etfSnapshots[0].proxy;delete f.policy.etfSnapshots[0].actualCompositionVerified;const a=calc(f);assert.equal(a.rows[0].evidenceKind,'actual_verified');assert.equal(a.rows[0].actualCompositionVerified,true);assert.equal(a.rows[0].sourceCompositionComplete,true);assert(!a.rows[0].proxy);});
test('render and production dual render explicitly show proxy date source benchmark and differences',()=>{const f=fixture(),a=calc(f),html=renderAiExposure(a);assert.match(html,/SYNTH 代理估算/);assert.match(html,/QQQ/);assert.match(html,/代理日期 2026-10-01/);assert.match(html,/Nasdaq-100/);assert.match(html,/https:\/\/example.org\/qqq-holdings/);assert.match(html,/https:\/\/example.org\/benchmark/);assert.match(html,/这不是 SYNTH 的已核实完整成分/);assert.match(html,/Different fees/);assert.match(html,/含代理估算/);const d=buildAiDualExposure(f.envelope,{cutoff,actualAllocation:a,policy:f.policy});assert.match(renderAiDualExposure(a,d),/SYNTH 代理估算/);assert.match(renderAiDualExposure(a,d),/含同基准代理估算（SYNTH）/);});
test('proxy expires at original100-day boundary without refreshing proxy source date',()=>{const f=fixture();f.policy.reviewBy='2027-02-01';for(const[date,usable]of[['2027-01-09',true],['2027-01-10',false]]){f.envelope.riskConstituents[0].valueDate=date;const r=calc(f,date).rows[0];assert.equal(r.etfAsOf!==null,usable);if(!usable){assert.equal(r.evidenceKind,null);assert(!r.proxy);assert.equal(r.uncoveredCents,'10000');}}});
test('physical proxy, false actual claim and missing provenance fail closed',()=>{for(const bad of[{basis:'physical-holdings'},{actualCompositionVerified:true},{actualCompositionVerified:undefined},{proxy:null},{evidenceKind:'verified-proxy'}]){const f=fixture();Object.assign(f.policy.etfSnapshots[0],bad);assert.throws(()=>calc(f),/proxy_invalid|evidence_kind_invalid/);}for(const key of['fundName','symbol','benchmark','benchmarkSource','limitations']){const f=fixture();f.policy.etfSnapshots[0].proxy[key]='';assert.throws(()=>calc(f),/proxy_invalid/);}});
test('unreviewed proxy issuer remains unknown and direct ticker does not gain binding',()=>{const f=fixture();f.envelope.riskConstituents[0]={...f.envelope.riskConstituents[0],instrumentId:'QQQ',symbol:'QQQ',assetType:'STK'};const a=calc(f);assert.equal(a.groups.find(g=>g.key==='pending').marketValueCents,'10000');});
test('proxy metadata is HTML escaped',()=>{const f=fixture();Object.assign(f.policy.etfSnapshots[0].proxy,{fundName:'<script>x</script>',limitations:'<img src=x onerror=alert(1)>'});const html=renderAiExposure(calc(f));assert.doesNotMatch(html,/<script|<img/);assert.match(html,/&lt;script/);});

test('actual partial evidence does not claim full actual composition verification',()=>{const f=fixture();delete f.policy.etfSnapshots[0].evidenceKind;delete f.policy.etfSnapshots[0].proxy;delete f.policy.etfSnapshots[0].actualCompositionVerified;f.policy.etfSnapshots[0].sourceCompositionComplete=false;const r=calc(f).rows[0];assert.equal(r.evidenceKind,'actual_verified');assert.equal(r.actualCompositionVerified,false);});

test('synthetic derivative overlay and derived-weight notes do not alter NAV allocations',()=>{const f=fixture(),before=calc(f);const s=f.policy.etfSnapshots[0];s.derivedWeightMethodNote='Synthetic documented method';s.derivedWeightPrecisionNote='Synthetic rounding limitation';s.economicUnclassifiedOverlay={kind:'index-futures',classification:'unknown',outsideNavAllocation:true,notionalNavPercent:3.5,mappingCaution:'Synthetic mapping uncertainty'};const after=calc(f);assert.deepEqual(after.groups,before.groups);assert.deepEqual(after.cash,before.cash);assert.equal(after.denominatorCents,before.denominatorCents);assert.match(renderAiExposure(after),/Synthetic documented method/);assert.match(renderAiExposure(after),/3.5000%/);assert.match(renderAiExposure(after),/Synthetic mapping uncertainty/);});
test('ambiguous overlay and incomplete derived-weight provenance are rejected',()=>{for(const fields of [{derivedWeightMethodNote:'Only half the provenance'},{economicUnclassifiedOverlay:{kind:'index-futures',classification:'unknown',outsideNavAllocation:true,notionalNavPercent:2,notionalNavRatioResearchIntervalPct:[1,3]}},{economicUnclassifiedOverlay:{kind:'index-futures',classification:'known',outsideNavAllocation:true,notionalNavPercent:2}}]){const f=fixture();Object.assign(f.policy.etfSnapshots[0],fields);assert.throws(()=>calc(f),/overlay_invalid|derived_weight_note_invalid/);}});

test('review priority source list labels proxy materials without asserting actual complete fund ownership',()=>{const f=fixture(),a=calc(f),p=buildAiReviewPriority(f.envelope,{cutoff,actualAllocation:a,policy:f.policy});assert.match(renderAiReviewPriority(p),/SYNTH 2026-10-01（代理资料）/);});
