import test from'node:test';import assert from'node:assert/strict';import fs from'node:fs';import os from'node:os';import path from'node:path';import{createHash}from'node:crypto';import{loadPrivateAiPolicy}from'./xuan-weekly-private-ai-snapshots.mjs';import{DEFAULT_POLICY}from'./xuan-weekly-ai-exposure.mjs';
function fixture(overrides={}){const directory=fs.mkdtempSync(path.join(os.tmpdir(),'weekly-private-synthetic-'));const old={instrumentId:'12',symbol:'TEST',fundName:'Synthetic fund',isin:'TEST00000001',basis:'physical-holdings',source:'https://example.org/old',asOf:'2026-08-31',holdings:[{issuerKey:'old-unknown',weightBp:100}]};const snapshot={...old,asOf:'2026-06-30',source:'https://example.org/official',holdings:[{issuerKey:'still-unknown',weightBp:5000}],...overrides};const bytes=JSON.stringify(snapshot);const sha256=createHash('sha256').update(bytes).digest('hex');const file=path.join(directory,sha256+'.json');fs.writeFileSync(file,bytes);const entry={instrumentId:'12',symbol:'TEST',asOf:'2026-06-30',sha256,maxBytes:2097152};return{directory,file,policy:{...structuredClone(DEFAULT_POLICY),etfSnapshots:[old]},manifest:{schema:'weekly-private-ai-snapshots.v1',entries:[entry]},snapshot,cleanup:()=>fs.rmSync(directory,{recursive:true,force:true})};}
const run=f=>loadPrivateAiPolicy({cutoff:'2026-10-02',directory:f.directory,policy:f.policy,manifest:f.manifest});
test('exact trusted private source replaces only matched target without mutating public fallback',()=>{const f=fixture();try{const out=run(f);assert.deepEqual(out.policy.etfSnapshots[0],f.snapshot);assert.equal(out.observations[0].status,'loaded');assert.equal(f.policy.etfSnapshots[0].asOf,'2026-08-31');}finally{f.cleanup();}});
test('missing directory/file and invalid bytes retain exact original partial source',()=>{for(const mode of['nodirectory','missing','tampered']){const f=fixture();try{if(mode==='missing')fs.unlinkSync(f.file);if(mode==='tampered')fs.appendFileSync(f.file,' ');const out=loadPrivateAiPolicy({cutoff:'2026-10-02',directory:mode==='nodirectory'?undefined:f.directory,policy:f.policy,manifest:f.manifest});assert.deepEqual(out.policy,f.policy);assert.equal(out.observations[0].status,mode==='nodirectory'?'missing':'unavailable_or_invalid');}finally{f.cleanup();}}});
test('future and source101days revert to public fallback;100days remains usable',()=>{const f=fixture();try{for(const[cutoff,status]of[['2026-06-29','outside_source_window'],['2026-10-08','loaded'],['2026-10-09','outside_source_window']]){const out=loadPrivateAiPolicy({cutoff,directory:f.directory,policy:f.policy,manifest:f.manifest});assert.equal(out.observations[0].status,status);if(status!=='loaded')assert.deepEqual(out.policy,f.policy);}}finally{f.cleanup();}});
test('correct hash does not authorize wrong fund, identity or date',()=>{for(const bad of[{fundName:'Other fund'},{isin:'OTHER0000001'},{symbol:'OTHER'},{instrumentId:'13'},{asOf:'2026-07-01'},{holdings:null}]){const f=fixture(bad);try{assert.equal(run(f).observations[0].status,'unavailable_or_invalid');assert.deepEqual(run(f).policy,f.policy);}finally{f.cleanup();}}});
test('symlinks and files above fixed size cap fail closed without exposing content',()=>{for(const mode of['symlink','oversize']){const f=fixture();try{if(mode==='symlink'){const alternate=f.file+'.real';fs.renameSync(f.file,alternate);fs.symlinkSync(alternate,f.file);}else fs.writeFileSync(f.file,'x'.repeat(2097153));const out=run(f);assert.equal(out.observations[0].status,'unavailable_or_invalid');assert.deepEqual(out.policy,f.policy);}finally{f.cleanup();}}});
test('manifest cannot change byte cap or duplicate targets',()=>{for(const mutate of[e=>e.maxBytes=99999999,e=>e.sha256='invalid']){const f=fixture();try{mutate(f.manifest.entries[0]);assert.throws(()=>run(f),/manifest_invalid/);}finally{f.cleanup();}}const f=fixture();try{f.manifest.entries.push({...f.manifest.entries[0]});assert.throws(()=>run(f),/manifest_invalid/);}finally{f.cleanup();}});
test('negative, duplicate and over100percent private weights fall back without breaking report',()=>{for(const holdings of[[{issuerKey:'unknown',weightBp:-1}],[{issuerKey:'same',weightBp:1000},{issuerKey:'same',weightBp:1000}],[{issuerKey:'one',weightBp:6000},{issuerKey:'two',weightBp:6000}],[{issuerKey:'null-weight',weightBp:null}]]){const f=fixture({holdings});try{const out=run(f);assert.equal(out.observations[0].status,'unavailable_or_invalid');assert.deepEqual(out.policy,f.policy);}finally{f.cleanup();}}});

function patchFixture(f,patch){const bytes=JSON.stringify(patch),sha256=createHash('sha256').update(bytes).digest('hex');fs.writeFileSync(path.join(f.directory,sha256+'.json'),bytes);f.manifest.policyPatch={sha256,maxBytes:2097152};return sha256;}
test('private reviewed classification patch and snapshot activate together without changing account or review scope',()=>{const f=fixture({holdings:[{issuerKey:'new-synthetic',weightBp:5000}]});try{patchFixture(f,{underlyingIssuers:[{key:'new-synthetic',issuer:'Synthetic issuer',group:'infrastructure',source:'https://example.org/business'}],issuerAliases:{'Synthetic issuer':'SYNTHETIC'}});const out=run(f);assert.equal(out.observations[0].status,'reviewed_policy_loaded');assert.equal(out.observations[1].status,'loaded');assert.equal(out.policy.underlyingIssuers[0].key,'new-synthetic');assert.deepEqual(out.policy.stocks,f.policy.stocks);assert.deepEqual(out.policy.directHoldings,f.policy.directHoldings);assert.equal(out.policy.reviewBy,f.policy.reviewBy);assert.equal(out.policy.reviewedOn,f.policy.reviewedOn);}finally{f.cleanup();}});
test('private patch cannot change money, direct identities, review expiry or new fund identity',()=>{for(const patch of[{stocks:[]},{directHoldings:[]},{reviewBy:'2099-01-01'},{nav:'999'},{etfSnapshots:[{instrumentId:'999',symbol:'OTHER'}]}]){const f=fixture();try{patchFixture(f,patch);const out=run(f);assert.deepEqual(out.policy,f.policy);assert.deepEqual(out.observations,[{status:'reviewed_policy_unavailable_or_invalid'}]);}finally{f.cleanup();}}});
test('missing patch prevents partial activation of source matrices',()=>{const f=fixture();try{const sha=patchFixture(f,{issuerAliases:{Synthetic:'TEST'}});fs.unlinkSync(path.join(f.directory,sha+'.json'));const out=run(f);assert.deepEqual(out.policy,f.policy);assert.deepEqual(out.observations,[{status:'reviewed_policy_unavailable_or_invalid'}]);}finally{f.cleanup();}});
